// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config_file_response.proto

package config_manage // import "github.com/polarismesh/specification/source/go/api/v1/config_manage"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ConfigSimpleResponse struct {
	Code                 *wrapperspb.UInt32Value `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ConfigSimpleResponse) Reset()         { *m = ConfigSimpleResponse{} }
func (m *ConfigSimpleResponse) String() string { return proto.CompactTextString(m) }
func (*ConfigSimpleResponse) ProtoMessage()    {}
func (*ConfigSimpleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_file_response_4f8b917eff92e7db, []int{0}
}
func (m *ConfigSimpleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigSimpleResponse.Unmarshal(m, b)
}
func (m *ConfigSimpleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigSimpleResponse.Marshal(b, m, deterministic)
}
func (dst *ConfigSimpleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigSimpleResponse.Merge(dst, src)
}
func (m *ConfigSimpleResponse) XXX_Size() int {
	return xxx_messageInfo_ConfigSimpleResponse.Size(m)
}
func (m *ConfigSimpleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigSimpleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigSimpleResponse proto.InternalMessageInfo

func (m *ConfigSimpleResponse) GetCode() *wrapperspb.UInt32Value {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *ConfigSimpleResponse) GetInfo() *wrapperspb.StringValue {
	if m != nil {
		return m.Info
	}
	return nil
}

type ConfigResponse struct {
	Code                     *wrapperspb.UInt32Value   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                     *wrapperspb.StringValue   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	ConfigFileGroup          *ConfigFileGroup          `protobuf:"bytes,3,opt,name=configFileGroup,proto3" json:"configFileGroup,omitempty"`
	ConfigFile               *ConfigFile               `protobuf:"bytes,4,opt,name=configFile,proto3" json:"configFile,omitempty"`
	ConfigFileRelease        *ConfigFileRelease        `protobuf:"bytes,5,opt,name=configFileRelease,proto3" json:"configFileRelease,omitempty"`
	ConfigFileReleaseHistory *ConfigFileReleaseHistory `protobuf:"bytes,6,opt,name=configFileReleaseHistory,proto3" json:"configFileReleaseHistory,omitempty"`
	ConfigFileTemplate       *ConfigFileTemplate       `protobuf:"bytes,7,opt,name=configFileTemplate,proto3" json:"configFileTemplate,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                  `json:"-"`
	XXX_unrecognized         []byte                    `json:"-"`
	XXX_sizecache            int32                     `json:"-"`
}

func (m *ConfigResponse) Reset()         { *m = ConfigResponse{} }
func (m *ConfigResponse) String() string { return proto.CompactTextString(m) }
func (*ConfigResponse) ProtoMessage()    {}
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_file_response_4f8b917eff92e7db, []int{1}
}
func (m *ConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigResponse.Unmarshal(m, b)
}
func (m *ConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigResponse.Marshal(b, m, deterministic)
}
func (dst *ConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigResponse.Merge(dst, src)
}
func (m *ConfigResponse) XXX_Size() int {
	return xxx_messageInfo_ConfigResponse.Size(m)
}
func (m *ConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigResponse proto.InternalMessageInfo

func (m *ConfigResponse) GetCode() *wrapperspb.UInt32Value {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *ConfigResponse) GetInfo() *wrapperspb.StringValue {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ConfigResponse) GetConfigFileGroup() *ConfigFileGroup {
	if m != nil {
		return m.ConfigFileGroup
	}
	return nil
}

func (m *ConfigResponse) GetConfigFile() *ConfigFile {
	if m != nil {
		return m.ConfigFile
	}
	return nil
}

func (m *ConfigResponse) GetConfigFileRelease() *ConfigFileRelease {
	if m != nil {
		return m.ConfigFileRelease
	}
	return nil
}

func (m *ConfigResponse) GetConfigFileReleaseHistory() *ConfigFileReleaseHistory {
	if m != nil {
		return m.ConfigFileReleaseHistory
	}
	return nil
}

func (m *ConfigResponse) GetConfigFileTemplate() *ConfigFileTemplate {
	if m != nil {
		return m.ConfigFileTemplate
	}
	return nil
}

type ConfigBatchWriteResponse struct {
	Code                 *wrapperspb.UInt32Value `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Total                *wrapperspb.UInt32Value `protobuf:"bytes,3,opt,name=total,proto3" json:"total,omitempty"`
	Responses            []*ConfigResponse       `protobuf:"bytes,4,rep,name=responses,proto3" json:"responses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ConfigBatchWriteResponse) Reset()         { *m = ConfigBatchWriteResponse{} }
func (m *ConfigBatchWriteResponse) String() string { return proto.CompactTextString(m) }
func (*ConfigBatchWriteResponse) ProtoMessage()    {}
func (*ConfigBatchWriteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_file_response_4f8b917eff92e7db, []int{2}
}
func (m *ConfigBatchWriteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigBatchWriteResponse.Unmarshal(m, b)
}
func (m *ConfigBatchWriteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigBatchWriteResponse.Marshal(b, m, deterministic)
}
func (dst *ConfigBatchWriteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigBatchWriteResponse.Merge(dst, src)
}
func (m *ConfigBatchWriteResponse) XXX_Size() int {
	return xxx_messageInfo_ConfigBatchWriteResponse.Size(m)
}
func (m *ConfigBatchWriteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigBatchWriteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigBatchWriteResponse proto.InternalMessageInfo

func (m *ConfigBatchWriteResponse) GetCode() *wrapperspb.UInt32Value {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *ConfigBatchWriteResponse) GetInfo() *wrapperspb.StringValue {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ConfigBatchWriteResponse) GetTotal() *wrapperspb.UInt32Value {
	if m != nil {
		return m.Total
	}
	return nil
}

func (m *ConfigBatchWriteResponse) GetResponses() []*ConfigResponse {
	if m != nil {
		return m.Responses
	}
	return nil
}

type ConfigBatchQueryResponse struct {
	Code                       *wrapperspb.UInt32Value     `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                       *wrapperspb.StringValue     `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Total                      *wrapperspb.UInt32Value     `protobuf:"bytes,3,opt,name=total,proto3" json:"total,omitempty"`
	ConfigFileGroups           []*ConfigFileGroup          `protobuf:"bytes,4,rep,name=configFileGroups,proto3" json:"configFileGroups,omitempty"`
	ConfigFiles                []*ConfigFile               `protobuf:"bytes,5,rep,name=configFiles,proto3" json:"configFiles,omitempty"`
	ConfigFileReleases         []*ConfigFileRelease        `protobuf:"bytes,6,rep,name=configFileReleases,proto3" json:"configFileReleases,omitempty"`
	ConfigFileReleaseHistories []*ConfigFileReleaseHistory `protobuf:"bytes,7,rep,name=configFileReleaseHistories,proto3" json:"configFileReleaseHistories,omitempty"`
	ConfigFileTemplates        []*ConfigFileTemplate       `protobuf:"bytes,8,rep,name=configFileTemplates,proto3" json:"configFileTemplates,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}                    `json:"-"`
	XXX_unrecognized           []byte                      `json:"-"`
	XXX_sizecache              int32                       `json:"-"`
}

func (m *ConfigBatchQueryResponse) Reset()         { *m = ConfigBatchQueryResponse{} }
func (m *ConfigBatchQueryResponse) String() string { return proto.CompactTextString(m) }
func (*ConfigBatchQueryResponse) ProtoMessage()    {}
func (*ConfigBatchQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_file_response_4f8b917eff92e7db, []int{3}
}
func (m *ConfigBatchQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigBatchQueryResponse.Unmarshal(m, b)
}
func (m *ConfigBatchQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigBatchQueryResponse.Marshal(b, m, deterministic)
}
func (dst *ConfigBatchQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigBatchQueryResponse.Merge(dst, src)
}
func (m *ConfigBatchQueryResponse) XXX_Size() int {
	return xxx_messageInfo_ConfigBatchQueryResponse.Size(m)
}
func (m *ConfigBatchQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigBatchQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigBatchQueryResponse proto.InternalMessageInfo

func (m *ConfigBatchQueryResponse) GetCode() *wrapperspb.UInt32Value {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *ConfigBatchQueryResponse) GetInfo() *wrapperspb.StringValue {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ConfigBatchQueryResponse) GetTotal() *wrapperspb.UInt32Value {
	if m != nil {
		return m.Total
	}
	return nil
}

func (m *ConfigBatchQueryResponse) GetConfigFileGroups() []*ConfigFileGroup {
	if m != nil {
		return m.ConfigFileGroups
	}
	return nil
}

func (m *ConfigBatchQueryResponse) GetConfigFiles() []*ConfigFile {
	if m != nil {
		return m.ConfigFiles
	}
	return nil
}

func (m *ConfigBatchQueryResponse) GetConfigFileReleases() []*ConfigFileRelease {
	if m != nil {
		return m.ConfigFileReleases
	}
	return nil
}

func (m *ConfigBatchQueryResponse) GetConfigFileReleaseHistories() []*ConfigFileReleaseHistory {
	if m != nil {
		return m.ConfigFileReleaseHistories
	}
	return nil
}

func (m *ConfigBatchQueryResponse) GetConfigFileTemplates() []*ConfigFileTemplate {
	if m != nil {
		return m.ConfigFileTemplates
	}
	return nil
}

type ConfigClientResponse struct {
	Code                 *wrapperspb.UInt32Value `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	ConfigFile           *ClientConfigFileInfo   `protobuf:"bytes,3,opt,name=configFile,proto3" json:"configFile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ConfigClientResponse) Reset()         { *m = ConfigClientResponse{} }
func (m *ConfigClientResponse) String() string { return proto.CompactTextString(m) }
func (*ConfigClientResponse) ProtoMessage()    {}
func (*ConfigClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_file_response_4f8b917eff92e7db, []int{4}
}
func (m *ConfigClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigClientResponse.Unmarshal(m, b)
}
func (m *ConfigClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigClientResponse.Marshal(b, m, deterministic)
}
func (dst *ConfigClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigClientResponse.Merge(dst, src)
}
func (m *ConfigClientResponse) XXX_Size() int {
	return xxx_messageInfo_ConfigClientResponse.Size(m)
}
func (m *ConfigClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigClientResponse proto.InternalMessageInfo

func (m *ConfigClientResponse) GetCode() *wrapperspb.UInt32Value {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *ConfigClientResponse) GetInfo() *wrapperspb.StringValue {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ConfigClientResponse) GetConfigFile() *ClientConfigFileInfo {
	if m != nil {
		return m.ConfigFile
	}
	return nil
}

type ConfigImportResponse struct {
	Code                 *wrapperspb.UInt32Value `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	CreateConfigFiles    []*ConfigFile           `protobuf:"bytes,3,rep,name=createConfigFiles,proto3" json:"createConfigFiles,omitempty"`
	SkipConfigFiles      []*ConfigFile           `protobuf:"bytes,4,rep,name=skipConfigFiles,proto3" json:"skipConfigFiles,omitempty"`
	OverwriteConfigFiles []*ConfigFile           `protobuf:"bytes,5,rep,name=overwriteConfigFiles,proto3" json:"overwriteConfigFiles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ConfigImportResponse) Reset()         { *m = ConfigImportResponse{} }
func (m *ConfigImportResponse) String() string { return proto.CompactTextString(m) }
func (*ConfigImportResponse) ProtoMessage()    {}
func (*ConfigImportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_file_response_4f8b917eff92e7db, []int{5}
}
func (m *ConfigImportResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigImportResponse.Unmarshal(m, b)
}
func (m *ConfigImportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigImportResponse.Marshal(b, m, deterministic)
}
func (dst *ConfigImportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigImportResponse.Merge(dst, src)
}
func (m *ConfigImportResponse) XXX_Size() int {
	return xxx_messageInfo_ConfigImportResponse.Size(m)
}
func (m *ConfigImportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigImportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigImportResponse proto.InternalMessageInfo

func (m *ConfigImportResponse) GetCode() *wrapperspb.UInt32Value {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *ConfigImportResponse) GetInfo() *wrapperspb.StringValue {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ConfigImportResponse) GetCreateConfigFiles() []*ConfigFile {
	if m != nil {
		return m.CreateConfigFiles
	}
	return nil
}

func (m *ConfigImportResponse) GetSkipConfigFiles() []*ConfigFile {
	if m != nil {
		return m.SkipConfigFiles
	}
	return nil
}

func (m *ConfigImportResponse) GetOverwriteConfigFiles() []*ConfigFile {
	if m != nil {
		return m.OverwriteConfigFiles
	}
	return nil
}

type ConfigExportResponse struct {
	Code                 *wrapperspb.UInt32Value `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Data                 *wrapperspb.BytesValue  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ConfigExportResponse) Reset()         { *m = ConfigExportResponse{} }
func (m *ConfigExportResponse) String() string { return proto.CompactTextString(m) }
func (*ConfigExportResponse) ProtoMessage()    {}
func (*ConfigExportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_file_response_4f8b917eff92e7db, []int{6}
}
func (m *ConfigExportResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigExportResponse.Unmarshal(m, b)
}
func (m *ConfigExportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigExportResponse.Marshal(b, m, deterministic)
}
func (dst *ConfigExportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigExportResponse.Merge(dst, src)
}
func (m *ConfigExportResponse) XXX_Size() int {
	return xxx_messageInfo_ConfigExportResponse.Size(m)
}
func (m *ConfigExportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigExportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigExportResponse proto.InternalMessageInfo

func (m *ConfigExportResponse) GetCode() *wrapperspb.UInt32Value {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *ConfigExportResponse) GetInfo() *wrapperspb.StringValue {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ConfigExportResponse) GetData() *wrapperspb.BytesValue {
	if m != nil {
		return m.Data
	}
	return nil
}

type ConfigEncryptAlgorithmResponse struct {
	Code                 *wrapperspb.UInt32Value   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 *wrapperspb.StringValue   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Algorithms           []*wrapperspb.StringValue `protobuf:"bytes,3,rep,name=algorithms,proto3" json:"algorithms,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ConfigEncryptAlgorithmResponse) Reset()         { *m = ConfigEncryptAlgorithmResponse{} }
func (m *ConfigEncryptAlgorithmResponse) String() string { return proto.CompactTextString(m) }
func (*ConfigEncryptAlgorithmResponse) ProtoMessage()    {}
func (*ConfigEncryptAlgorithmResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_file_response_4f8b917eff92e7db, []int{7}
}
func (m *ConfigEncryptAlgorithmResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigEncryptAlgorithmResponse.Unmarshal(m, b)
}
func (m *ConfigEncryptAlgorithmResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigEncryptAlgorithmResponse.Marshal(b, m, deterministic)
}
func (dst *ConfigEncryptAlgorithmResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigEncryptAlgorithmResponse.Merge(dst, src)
}
func (m *ConfigEncryptAlgorithmResponse) XXX_Size() int {
	return xxx_messageInfo_ConfigEncryptAlgorithmResponse.Size(m)
}
func (m *ConfigEncryptAlgorithmResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigEncryptAlgorithmResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigEncryptAlgorithmResponse proto.InternalMessageInfo

func (m *ConfigEncryptAlgorithmResponse) GetCode() *wrapperspb.UInt32Value {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *ConfigEncryptAlgorithmResponse) GetInfo() *wrapperspb.StringValue {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ConfigEncryptAlgorithmResponse) GetAlgorithms() []*wrapperspb.StringValue {
	if m != nil {
		return m.Algorithms
	}
	return nil
}

type ConfigDiscoverResponse struct {
	Code                 uint32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 string                  `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Revision             string                  `protobuf:"bytes,3,opt,name=revision,proto3" json:"revision,omitempty"`
	Type                 ConfigDiscoverType      `protobuf:"varint,4,opt,name=type,proto3,enum=v1.ConfigDiscoverType" json:"type,omitempty"`
	ConfigFile           *ClientConfigFileInfo   `protobuf:"bytes,5,opt,name=config_file,json=configFile,proto3" json:"config_file,omitempty"`
	ConfigFileNames      []*ClientConfigFileInfo `protobuf:"bytes,6,rep,name=config_file_names,json=configFileNames,proto3" json:"config_file_names,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ConfigDiscoverResponse) Reset()         { *m = ConfigDiscoverResponse{} }
func (m *ConfigDiscoverResponse) String() string { return proto.CompactTextString(m) }
func (*ConfigDiscoverResponse) ProtoMessage()    {}
func (*ConfigDiscoverResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_file_response_4f8b917eff92e7db, []int{8}
}
func (m *ConfigDiscoverResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigDiscoverResponse.Unmarshal(m, b)
}
func (m *ConfigDiscoverResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigDiscoverResponse.Marshal(b, m, deterministic)
}
func (dst *ConfigDiscoverResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigDiscoverResponse.Merge(dst, src)
}
func (m *ConfigDiscoverResponse) XXX_Size() int {
	return xxx_messageInfo_ConfigDiscoverResponse.Size(m)
}
func (m *ConfigDiscoverResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigDiscoverResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigDiscoverResponse proto.InternalMessageInfo

func (m *ConfigDiscoverResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ConfigDiscoverResponse) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *ConfigDiscoverResponse) GetRevision() string {
	if m != nil {
		return m.Revision
	}
	return ""
}

func (m *ConfigDiscoverResponse) GetType() ConfigDiscoverType {
	if m != nil {
		return m.Type
	}
	return ConfigDiscoverType_UNKNOWN
}

func (m *ConfigDiscoverResponse) GetConfigFile() *ClientConfigFileInfo {
	if m != nil {
		return m.ConfigFile
	}
	return nil
}

func (m *ConfigDiscoverResponse) GetConfigFileNames() []*ClientConfigFileInfo {
	if m != nil {
		return m.ConfigFileNames
	}
	return nil
}

func init() {
	proto.RegisterType((*ConfigSimpleResponse)(nil), "v1.ConfigSimpleResponse")
	proto.RegisterType((*ConfigResponse)(nil), "v1.ConfigResponse")
	proto.RegisterType((*ConfigBatchWriteResponse)(nil), "v1.ConfigBatchWriteResponse")
	proto.RegisterType((*ConfigBatchQueryResponse)(nil), "v1.ConfigBatchQueryResponse")
	proto.RegisterType((*ConfigClientResponse)(nil), "v1.ConfigClientResponse")
	proto.RegisterType((*ConfigImportResponse)(nil), "v1.ConfigImportResponse")
	proto.RegisterType((*ConfigExportResponse)(nil), "v1.ConfigExportResponse")
	proto.RegisterType((*ConfigEncryptAlgorithmResponse)(nil), "v1.ConfigEncryptAlgorithmResponse")
	proto.RegisterType((*ConfigDiscoverResponse)(nil), "v1.ConfigDiscoverResponse")
}

func init() {
	proto.RegisterFile("config_file_response.proto", fileDescriptor_config_file_response_4f8b917eff92e7db)
}

var fileDescriptor_config_file_response_4f8b917eff92e7db = []byte{
	// 761 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xcd, 0x6e, 0xd3, 0x4a,
	0x14, 0x56, 0x7e, 0xfa, 0x37, 0xd5, 0x6d, 0x6f, 0xa7, 0xbd, 0xbd, 0xa3, 0xdc, 0xab, 0xaa, 0xf2,
	0xaa, 0x62, 0x61, 0xb7, 0xa9, 0x84, 0x8a, 0x04, 0x42, 0x24, 0x6d, 0x69, 0x37, 0x08, 0xdc, 0xf2,
	0x23, 0x84, 0x54, 0x4d, 0xdd, 0x13, 0x67, 0x84, 0xed, 0x19, 0xcd, 0x4c, 0x52, 0xc2, 0x1b, 0xb0,
	0x47, 0xbc, 0x04, 0x5b, 0xc4, 0x03, 0xb0, 0xe4, 0x39, 0x78, 0x10, 0xe4, 0xb1, 0x9d, 0x38, 0xb1,
	0x13, 0x58, 0x45, 0x2c, 0x7d, 0xe6, 0xfb, 0xbe, 0x39, 0x67, 0xce, 0x37, 0xc7, 0x83, 0x1a, 0x1e,
	0x8f, 0x3a, 0xcc, 0xbf, 0xea, 0xb0, 0x00, 0xae, 0x24, 0x28, 0xc1, 0x23, 0x05, 0xb6, 0x90, 0x5c,
	0x73, 0x5c, 0xed, 0x1f, 0x34, 0x76, 0x7c, 0xce, 0xfd, 0x00, 0x1c, 0x13, 0xb9, 0xee, 0x75, 0x9c,
	0x5b, 0x49, 0x85, 0x00, 0xa9, 0x12, 0x4c, 0x63, 0x23, 0xc7, 0x4f, 0x42, 0xd6, 0x7b, 0xb4, 0xd5,
	0x36, 0xc1, 0x0b, 0x16, 0x8a, 0x00, 0xdc, 0x54, 0x14, 0xef, 0xa3, 0xba, 0xc7, 0x6f, 0x80, 0x54,
	0x76, 0x2b, 0x7b, 0xab, 0xcd, 0xff, 0xed, 0x44, 0xd9, 0xce, 0x94, 0xed, 0xe7, 0xe7, 0x91, 0x3e,
	0x6c, 0xbe, 0xa0, 0x41, 0x0f, 0x5c, 0x83, 0x8c, 0x19, 0x2c, 0xea, 0x70, 0x52, 0x9d, 0xc2, 0xb8,
	0xd0, 0x92, 0x45, 0x7e, 0xca, 0x88, 0x91, 0xd6, 0xf7, 0x1a, 0x5a, 0x4b, 0x36, 0x9f, 0xe7, 0xb6,
	0xf8, 0x01, 0x5a, 0x4f, 0xce, 0xe1, 0x94, 0x05, 0xf0, 0x58, 0xf2, 0x9e, 0x20, 0x35, 0x43, 0xde,
	0xb4, 0xfb, 0x07, 0x76, 0x7b, 0x7c, 0xc9, 0x9d, 0xc4, 0x62, 0x1b, 0xa1, 0x51, 0x88, 0xd4, 0x0d,
	0x73, 0x6d, 0x9c, 0xe9, 0xe6, 0x10, 0xb8, 0x8d, 0x36, 0x46, 0x5f, 0x2e, 0x04, 0x40, 0x15, 0x90,
	0x05, 0x43, 0xfb, 0x67, 0x82, 0x96, 0x2c, 0xba, 0x45, 0x3c, 0x7e, 0x85, 0x48, 0x21, 0x78, 0xc6,
	0x94, 0xe6, 0x72, 0x40, 0x16, 0xd3, 0xca, 0xcb, 0xb4, 0x52, 0x8c, 0x3b, 0x95, 0x8d, 0x4f, 0x11,
	0x1e, 0xad, 0x5d, 0x42, 0x28, 0x02, 0xaa, 0x81, 0x2c, 0x19, 0xcd, 0xed, 0x71, 0xcd, 0x6c, 0xd5,
	0x2d, 0x61, 0x58, 0x3f, 0x2a, 0x88, 0x24, 0xd0, 0x16, 0xd5, 0x5e, 0xf7, 0xa5, 0x64, 0x7a, 0xae,
	0x6e, 0xc2, 0x4d, 0xb4, 0xa0, 0xb9, 0xa6, 0x41, 0xda, 0xcc, 0xd9, 0x9b, 0x24, 0x50, 0xbc, 0x8f,
	0x56, 0xb2, 0x6b, 0xa4, 0x48, 0x7d, 0xb7, 0xb6, 0xb7, 0xda, 0xc4, 0xa3, 0x9a, 0xb3, 0xf4, 0xdd,
	0x11, 0xc8, 0xfa, 0x58, 0x1f, 0x2b, 0xf3, 0x59, 0x0f, 0xe4, 0xe0, 0x8f, 0x2f, 0xf3, 0x21, 0xfa,
	0x7b, 0xc2, 0xc5, 0x59, 0xb5, 0xa5, 0x96, 0x2f, 0x80, 0xf1, 0x3e, 0x5a, 0x1d, 0xc5, 0x14, 0x59,
	0x30, 0xdc, 0x49, 0xd3, 0xe7, 0x21, 0xf8, 0x24, 0x6f, 0xab, 0xd4, 0x72, 0x8a, 0x2c, 0x1a, 0xe2,
	0x14, 0xdb, 0x97, 0x10, 0xf0, 0x9b, 0x6c, 0xe6, 0x15, 0x9c, 0xcb, 0x40, 0x91, 0x25, 0x23, 0x37,
	0xdb, 0xf9, 0x33, 0xf8, 0xf8, 0x0c, 0x6d, 0x16, 0x9d, 0xac, 0xc8, 0xb2, 0x91, 0x9d, 0x66, 0xfe,
	0x32, 0x8a, 0xf5, 0xa5, 0x92, 0xcd, 0xd1, 0x76, 0xc0, 0x20, 0xd2, 0x73, 0xb5, 0xc4, 0xd1, 0xd8,
	0x44, 0x4a, 0x7c, 0x41, 0x4c, 0xf6, 0x26, 0x97, 0x51, 0x0d, 0xe7, 0x51, 0x87, 0xe7, 0x67, 0x93,
	0xf5, 0xb5, 0x9a, 0xa5, 0x7d, 0x1e, 0x0a, 0x2e, 0xe7, 0x9b, 0xf6, 0x7d, 0xb4, 0xe1, 0x49, 0xa0,
	0x1a, 0xda, 0x39, 0x6b, 0xd5, 0x4a, 0xad, 0x55, 0x04, 0xe2, 0x23, 0xb4, 0xae, 0xde, 0x32, 0x91,
	0xe7, 0xd6, 0x4b, 0xb9, 0x93, 0x30, 0xdc, 0x42, 0x5b, 0xbc, 0x0f, 0xf2, 0x36, 0x9e, 0x50, 0xed,
	0x5f, 0xba, 0xba, 0x14, 0x6b, 0x7d, 0x1e, 0xf6, 0xfb, 0xe4, 0xdd, 0xdc, 0x0f, 0xce, 0x41, 0xf5,
	0x1b, 0xaa, 0x69, 0xda, 0xe9, 0xff, 0x0a, 0x8c, 0xd6, 0x40, 0x83, 0x4a, 0x09, 0x31, 0xd0, 0xfa,
	0x56, 0x41, 0x3b, 0x69, 0xb6, 0x91, 0x27, 0x07, 0x42, 0x3f, 0x0a, 0x7c, 0x2e, 0x99, 0xee, 0x86,
	0x73, 0x6e, 0x38, 0xa2, 0xd9, 0xc6, 0x59, 0xa7, 0x67, 0xf3, 0x72, 0x78, 0xeb, 0x43, 0x15, 0x6d,
	0x27, 0x45, 0x1c, 0x33, 0xe5, 0xc5, 0x5d, 0x19, 0x26, 0x8f, 0x73, 0xc9, 0xff, 0x95, 0xa6, 0x87,
	0x73, 0xe9, 0xad, 0xa4, 0x09, 0x34, 0xd0, 0xb2, 0x84, 0x3e, 0x53, 0x8c, 0x47, 0xe6, 0xf0, 0x56,
	0xdc, 0xe1, 0x37, 0xbe, 0x83, 0xea, 0x7a, 0x20, 0x92, 0x1f, 0xfa, 0x5a, 0xfe, 0xf2, 0x67, 0xbb,
	0x5d, 0x0e, 0x04, 0xb8, 0x06, 0x83, 0xef, 0x65, 0xe3, 0xd0, 0xbc, 0xa4, 0xd2, 0x9f, 0xf9, 0x6f,
	0xdd, 0x38, 0x7c, 0x8c, 0xf2, 0x8f, 0xb0, 0xab, 0x88, 0x86, 0xc3, 0xb1, 0x38, 0x5d, 0x20, 0xf7,
	0x06, 0x79, 0x12, 0x13, 0x5a, 0x9f, 0x2a, 0xe8, 0xae, 0xc7, 0x43, 0x5b, 0x43, 0xe4, 0x41, 0xa4,
	0x6d, 0xc1, 0x03, 0x2a, 0x99, 0xb2, 0x95, 0x00, 0x8f, 0x75, 0x98, 0x47, 0x35, 0xe3, 0x91, 0x4d,
	0x05, 0x8b, 0x25, 0x13, 0xb2, 0x1d, 0xd2, 0x88, 0xfa, 0xd0, 0xfa, 0x37, 0x3f, 0x29, 0x93, 0xf3,
	0x7b, 0x1a, 0x1f, 0xfd, 0xeb, 0xb6, 0xcf, 0x74, 0xb7, 0x77, 0x6d, 0x7b, 0x3c, 0x74, 0x52, 0xbd,
	0x10, 0x54, 0xd7, 0x19, 0xd3, 0x74, 0x14, 0xef, 0x49, 0x0f, 0x1c, 0x9f, 0x3b, 0x54, 0x30, 0xa7,
	0x7f, 0xe0, 0xa4, 0xd5, 0x24, 0xea, 0xd7, 0x8b, 0xa6, 0x8d, 0x87, 0x3f, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x14, 0xa1, 0xe5, 0xe6, 0xaa, 0x0a, 0x00, 0x00,
}
