// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config_file.proto

package config_manage // import "github.com/polarismesh/specification/source/go/api/v1/config_manage"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ConfigFileGroup struct {
	Id                   *wrapperspb.UInt64Value   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 *wrapperspb.StringValue   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace            *wrapperspb.StringValue   `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Comment              *wrapperspb.StringValue   `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	CreateTime           *wrapperspb.StringValue   `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	CreateBy             *wrapperspb.StringValue   `protobuf:"bytes,6,opt,name=create_by,json=createBy,proto3" json:"create_by,omitempty"`
	ModifyTime           *wrapperspb.StringValue   `protobuf:"bytes,7,opt,name=modify_time,json=modifyTime,proto3" json:"modify_time,omitempty"`
	ModifyBy             *wrapperspb.StringValue   `protobuf:"bytes,8,opt,name=modify_by,json=modifyBy,proto3" json:"modify_by,omitempty"`
	FileCount            *wrapperspb.UInt64Value   `protobuf:"bytes,9,opt,name=fileCount,proto3" json:"fileCount,omitempty"`
	UserIds              []*wrapperspb.StringValue `protobuf:"bytes,10,rep,name=user_ids,proto3" json:"user_ids,omitempty"`
	GroupIds             []*wrapperspb.StringValue `protobuf:"bytes,11,rep,name=group_ids,proto3" json:"group_ids,omitempty"`
	RemoveUserIds        []*wrapperspb.StringValue `protobuf:"bytes,13,rep,name=remove_user_ids,proto3" json:"remove_user_ids,omitempty"`
	RemoveGroupIds       []*wrapperspb.StringValue `protobuf:"bytes,14,rep,name=remove_group_ids,proto3" json:"remove_group_ids,omitempty"`
	Editable             *wrapperspb.BoolValue     `protobuf:"bytes,15,opt,name=editable,proto3" json:"editable,omitempty"`
	Owner                *wrapperspb.StringValue   `protobuf:"bytes,16,opt,name=owner,proto3" json:"owner,omitempty"`
	Business             *wrapperspb.StringValue   `protobuf:"bytes,17,opt,name=business,proto3" json:"business,omitempty"`
	Department           *wrapperspb.StringValue   `protobuf:"bytes,18,opt,name=department,proto3" json:"department,omitempty"`
	Metadata             map[string]string         `protobuf:"bytes,19,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ConfigFileGroup) Reset()         { *m = ConfigFileGroup{} }
func (m *ConfigFileGroup) String() string { return proto.CompactTextString(m) }
func (*ConfigFileGroup) ProtoMessage()    {}
func (*ConfigFileGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_file_72bb0a0c8382e743, []int{0}
}
func (m *ConfigFileGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigFileGroup.Unmarshal(m, b)
}
func (m *ConfigFileGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigFileGroup.Marshal(b, m, deterministic)
}
func (dst *ConfigFileGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigFileGroup.Merge(dst, src)
}
func (m *ConfigFileGroup) XXX_Size() int {
	return xxx_messageInfo_ConfigFileGroup.Size(m)
}
func (m *ConfigFileGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigFileGroup.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigFileGroup proto.InternalMessageInfo

func (m *ConfigFileGroup) GetId() *wrapperspb.UInt64Value {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ConfigFileGroup) GetName() *wrapperspb.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *ConfigFileGroup) GetNamespace() *wrapperspb.StringValue {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *ConfigFileGroup) GetComment() *wrapperspb.StringValue {
	if m != nil {
		return m.Comment
	}
	return nil
}

func (m *ConfigFileGroup) GetCreateTime() *wrapperspb.StringValue {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *ConfigFileGroup) GetCreateBy() *wrapperspb.StringValue {
	if m != nil {
		return m.CreateBy
	}
	return nil
}

func (m *ConfigFileGroup) GetModifyTime() *wrapperspb.StringValue {
	if m != nil {
		return m.ModifyTime
	}
	return nil
}

func (m *ConfigFileGroup) GetModifyBy() *wrapperspb.StringValue {
	if m != nil {
		return m.ModifyBy
	}
	return nil
}

func (m *ConfigFileGroup) GetFileCount() *wrapperspb.UInt64Value {
	if m != nil {
		return m.FileCount
	}
	return nil
}

func (m *ConfigFileGroup) GetUserIds() []*wrapperspb.StringValue {
	if m != nil {
		return m.UserIds
	}
	return nil
}

func (m *ConfigFileGroup) GetGroupIds() []*wrapperspb.StringValue {
	if m != nil {
		return m.GroupIds
	}
	return nil
}

func (m *ConfigFileGroup) GetRemoveUserIds() []*wrapperspb.StringValue {
	if m != nil {
		return m.RemoveUserIds
	}
	return nil
}

func (m *ConfigFileGroup) GetRemoveGroupIds() []*wrapperspb.StringValue {
	if m != nil {
		return m.RemoveGroupIds
	}
	return nil
}

func (m *ConfigFileGroup) GetEditable() *wrapperspb.BoolValue {
	if m != nil {
		return m.Editable
	}
	return nil
}

func (m *ConfigFileGroup) GetOwner() *wrapperspb.StringValue {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *ConfigFileGroup) GetBusiness() *wrapperspb.StringValue {
	if m != nil {
		return m.Business
	}
	return nil
}

func (m *ConfigFileGroup) GetDepartment() *wrapperspb.StringValue {
	if m != nil {
		return m.Department
	}
	return nil
}

func (m *ConfigFileGroup) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type ConfigFile struct {
	Id          *wrapperspb.UInt64Value `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace   *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Group       *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=group,proto3" json:"group,omitempty"`
	Content     *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Format      *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=format,proto3" json:"format,omitempty"`
	Comment     *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=comment,proto3" json:"comment,omitempty"`
	Status      *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Tags        []*ConfigFileTag        `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	CreateTime  *wrapperspb.StringValue `protobuf:"bytes,10,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	CreateBy    *wrapperspb.StringValue `protobuf:"bytes,11,opt,name=create_by,json=createBy,proto3" json:"create_by,omitempty"`
	ModifyTime  *wrapperspb.StringValue `protobuf:"bytes,12,opt,name=modify_time,json=modifyTime,proto3" json:"modify_time,omitempty"`
	ModifyBy    *wrapperspb.StringValue `protobuf:"bytes,13,opt,name=modify_by,json=modifyBy,proto3" json:"modify_by,omitempty"`
	ReleaseTime *wrapperspb.StringValue `protobuf:"bytes,14,opt,name=release_time,json=releaseTime,proto3" json:"release_time,omitempty"`
	ReleaseBy   *wrapperspb.StringValue `protobuf:"bytes,15,opt,name=release_by,json=releaseBy,proto3" json:"release_by,omitempty"`
	// 是否为加密配置文件
	Encrypted *wrapperspb.BoolValue `protobuf:"bytes,16,opt,name=encrypted,proto3" json:"encrypted,omitempty"`
	// 加密算法
	EncryptAlgo          *wrapperspb.StringValue `protobuf:"bytes,17,opt,name=encrypt_algo,json=encryptAlgo,proto3" json:"encrypt_algo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ConfigFile) Reset()         { *m = ConfigFile{} }
func (m *ConfigFile) String() string { return proto.CompactTextString(m) }
func (*ConfigFile) ProtoMessage()    {}
func (*ConfigFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_file_72bb0a0c8382e743, []int{1}
}
func (m *ConfigFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigFile.Unmarshal(m, b)
}
func (m *ConfigFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigFile.Marshal(b, m, deterministic)
}
func (dst *ConfigFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigFile.Merge(dst, src)
}
func (m *ConfigFile) XXX_Size() int {
	return xxx_messageInfo_ConfigFile.Size(m)
}
func (m *ConfigFile) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigFile.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigFile proto.InternalMessageInfo

func (m *ConfigFile) GetId() *wrapperspb.UInt64Value {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ConfigFile) GetName() *wrapperspb.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *ConfigFile) GetNamespace() *wrapperspb.StringValue {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *ConfigFile) GetGroup() *wrapperspb.StringValue {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *ConfigFile) GetContent() *wrapperspb.StringValue {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *ConfigFile) GetFormat() *wrapperspb.StringValue {
	if m != nil {
		return m.Format
	}
	return nil
}

func (m *ConfigFile) GetComment() *wrapperspb.StringValue {
	if m != nil {
		return m.Comment
	}
	return nil
}

func (m *ConfigFile) GetStatus() *wrapperspb.StringValue {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ConfigFile) GetTags() []*ConfigFileTag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *ConfigFile) GetCreateTime() *wrapperspb.StringValue {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *ConfigFile) GetCreateBy() *wrapperspb.StringValue {
	if m != nil {
		return m.CreateBy
	}
	return nil
}

func (m *ConfigFile) GetModifyTime() *wrapperspb.StringValue {
	if m != nil {
		return m.ModifyTime
	}
	return nil
}

func (m *ConfigFile) GetModifyBy() *wrapperspb.StringValue {
	if m != nil {
		return m.ModifyBy
	}
	return nil
}

func (m *ConfigFile) GetReleaseTime() *wrapperspb.StringValue {
	if m != nil {
		return m.ReleaseTime
	}
	return nil
}

func (m *ConfigFile) GetReleaseBy() *wrapperspb.StringValue {
	if m != nil {
		return m.ReleaseBy
	}
	return nil
}

func (m *ConfigFile) GetEncrypted() *wrapperspb.BoolValue {
	if m != nil {
		return m.Encrypted
	}
	return nil
}

func (m *ConfigFile) GetEncryptAlgo() *wrapperspb.StringValue {
	if m != nil {
		return m.EncryptAlgo
	}
	return nil
}

type ConfigFileTag struct {
	Key                  *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ConfigFileTag) Reset()         { *m = ConfigFileTag{} }
func (m *ConfigFileTag) String() string { return proto.CompactTextString(m) }
func (*ConfigFileTag) ProtoMessage()    {}
func (*ConfigFileTag) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_file_72bb0a0c8382e743, []int{2}
}
func (m *ConfigFileTag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigFileTag.Unmarshal(m, b)
}
func (m *ConfigFileTag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigFileTag.Marshal(b, m, deterministic)
}
func (dst *ConfigFileTag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigFileTag.Merge(dst, src)
}
func (m *ConfigFileTag) XXX_Size() int {
	return xxx_messageInfo_ConfigFileTag.Size(m)
}
func (m *ConfigFileTag) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigFileTag.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigFileTag proto.InternalMessageInfo

func (m *ConfigFileTag) GetKey() *wrapperspb.StringValue {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ConfigFileTag) GetValue() *wrapperspb.StringValue {
	if m != nil {
		return m.Value
	}
	return nil
}

type ConfigFileRelease struct {
	Id         *wrapperspb.UInt64Value `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace  *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Group      *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=group,proto3" json:"group,omitempty"`
	FileName   *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Content    *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Comment    *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=comment,proto3" json:"comment,omitempty"`
	Md5        *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=md5,proto3" json:"md5,omitempty"`
	Version    *wrapperspb.UInt64Value `protobuf:"bytes,9,opt,name=version,proto3" json:"version,omitempty"`
	CreateTime *wrapperspb.StringValue `protobuf:"bytes,10,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	CreateBy   *wrapperspb.StringValue `protobuf:"bytes,11,opt,name=create_by,json=createBy,proto3" json:"create_by,omitempty"`
	ModifyTime *wrapperspb.StringValue `protobuf:"bytes,12,opt,name=modify_time,json=modifyTime,proto3" json:"modify_time,omitempty"`
	ModifyBy   *wrapperspb.StringValue `protobuf:"bytes,13,opt,name=modify_by,json=modifyBy,proto3" json:"modify_by,omitempty"`
	Tags       []*ConfigFileTag        `protobuf:"bytes,14,rep,name=tags,proto3" json:"tags,omitempty"`
	// 当前生效配置
	Active               *wrapperspb.BoolValue   `protobuf:"bytes,15,opt,name=active,proto3" json:"active,omitempty"`
	Format               *wrapperspb.StringValue `protobuf:"bytes,16,opt,name=format,proto3" json:"format,omitempty"`
	ReleaseDescription   *wrapperspb.StringValue `protobuf:"bytes,17,opt,name=release_description,json=releaseDescription,proto3" json:"release_description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ConfigFileRelease) Reset()         { *m = ConfigFileRelease{} }
func (m *ConfigFileRelease) String() string { return proto.CompactTextString(m) }
func (*ConfigFileRelease) ProtoMessage()    {}
func (*ConfigFileRelease) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_file_72bb0a0c8382e743, []int{3}
}
func (m *ConfigFileRelease) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigFileRelease.Unmarshal(m, b)
}
func (m *ConfigFileRelease) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigFileRelease.Marshal(b, m, deterministic)
}
func (dst *ConfigFileRelease) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigFileRelease.Merge(dst, src)
}
func (m *ConfigFileRelease) XXX_Size() int {
	return xxx_messageInfo_ConfigFileRelease.Size(m)
}
func (m *ConfigFileRelease) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigFileRelease.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigFileRelease proto.InternalMessageInfo

func (m *ConfigFileRelease) GetId() *wrapperspb.UInt64Value {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ConfigFileRelease) GetName() *wrapperspb.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *ConfigFileRelease) GetNamespace() *wrapperspb.StringValue {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *ConfigFileRelease) GetGroup() *wrapperspb.StringValue {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *ConfigFileRelease) GetFileName() *wrapperspb.StringValue {
	if m != nil {
		return m.FileName
	}
	return nil
}

func (m *ConfigFileRelease) GetContent() *wrapperspb.StringValue {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *ConfigFileRelease) GetComment() *wrapperspb.StringValue {
	if m != nil {
		return m.Comment
	}
	return nil
}

func (m *ConfigFileRelease) GetMd5() *wrapperspb.StringValue {
	if m != nil {
		return m.Md5
	}
	return nil
}

func (m *ConfigFileRelease) GetVersion() *wrapperspb.UInt64Value {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *ConfigFileRelease) GetCreateTime() *wrapperspb.StringValue {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *ConfigFileRelease) GetCreateBy() *wrapperspb.StringValue {
	if m != nil {
		return m.CreateBy
	}
	return nil
}

func (m *ConfigFileRelease) GetModifyTime() *wrapperspb.StringValue {
	if m != nil {
		return m.ModifyTime
	}
	return nil
}

func (m *ConfigFileRelease) GetModifyBy() *wrapperspb.StringValue {
	if m != nil {
		return m.ModifyBy
	}
	return nil
}

func (m *ConfigFileRelease) GetTags() []*ConfigFileTag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *ConfigFileRelease) GetActive() *wrapperspb.BoolValue {
	if m != nil {
		return m.Active
	}
	return nil
}

func (m *ConfigFileRelease) GetFormat() *wrapperspb.StringValue {
	if m != nil {
		return m.Format
	}
	return nil
}

func (m *ConfigFileRelease) GetReleaseDescription() *wrapperspb.StringValue {
	if m != nil {
		return m.ReleaseDescription
	}
	return nil
}

type ConfigFileReleaseHistory struct {
	Id         *wrapperspb.UInt64Value `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace  *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Group      *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=group,proto3" json:"group,omitempty"`
	FileName   *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Content    *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Format     *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=format,proto3" json:"format,omitempty"`
	Comment    *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=comment,proto3" json:"comment,omitempty"`
	Md5        *wrapperspb.StringValue `protobuf:"bytes,9,opt,name=md5,proto3" json:"md5,omitempty"`
	Type       *wrapperspb.StringValue `protobuf:"bytes,10,opt,name=type,proto3" json:"type,omitempty"`
	Status     *wrapperspb.StringValue `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	Tags       []*ConfigFileTag        `protobuf:"bytes,12,rep,name=tags,proto3" json:"tags,omitempty"`
	CreateTime *wrapperspb.StringValue `protobuf:"bytes,13,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	CreateBy   *wrapperspb.StringValue `protobuf:"bytes,14,opt,name=create_by,json=createBy,proto3" json:"create_by,omitempty"`
	ModifyTime *wrapperspb.StringValue `protobuf:"bytes,15,opt,name=modify_time,json=modifyTime,proto3" json:"modify_time,omitempty"`
	ModifyBy   *wrapperspb.StringValue `protobuf:"bytes,16,opt,name=modify_by,json=modifyBy,proto3" json:"modify_by,omitempty"`
	// 配置发布失败的原因
	Reason               *wrapperspb.StringValue `protobuf:"bytes,17,opt,name=reason,proto3" json:"reason,omitempty"`
	ReleaseDescription   *wrapperspb.StringValue `protobuf:"bytes,18,opt,name=release_description,json=releaseDescription,proto3" json:"release_description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ConfigFileReleaseHistory) Reset()         { *m = ConfigFileReleaseHistory{} }
func (m *ConfigFileReleaseHistory) String() string { return proto.CompactTextString(m) }
func (*ConfigFileReleaseHistory) ProtoMessage()    {}
func (*ConfigFileReleaseHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_file_72bb0a0c8382e743, []int{4}
}
func (m *ConfigFileReleaseHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigFileReleaseHistory.Unmarshal(m, b)
}
func (m *ConfigFileReleaseHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigFileReleaseHistory.Marshal(b, m, deterministic)
}
func (dst *ConfigFileReleaseHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigFileReleaseHistory.Merge(dst, src)
}
func (m *ConfigFileReleaseHistory) XXX_Size() int {
	return xxx_messageInfo_ConfigFileReleaseHistory.Size(m)
}
func (m *ConfigFileReleaseHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigFileReleaseHistory.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigFileReleaseHistory proto.InternalMessageInfo

func (m *ConfigFileReleaseHistory) GetId() *wrapperspb.UInt64Value {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ConfigFileReleaseHistory) GetName() *wrapperspb.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *ConfigFileReleaseHistory) GetNamespace() *wrapperspb.StringValue {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *ConfigFileReleaseHistory) GetGroup() *wrapperspb.StringValue {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *ConfigFileReleaseHistory) GetFileName() *wrapperspb.StringValue {
	if m != nil {
		return m.FileName
	}
	return nil
}

func (m *ConfigFileReleaseHistory) GetContent() *wrapperspb.StringValue {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *ConfigFileReleaseHistory) GetFormat() *wrapperspb.StringValue {
	if m != nil {
		return m.Format
	}
	return nil
}

func (m *ConfigFileReleaseHistory) GetComment() *wrapperspb.StringValue {
	if m != nil {
		return m.Comment
	}
	return nil
}

func (m *ConfigFileReleaseHistory) GetMd5() *wrapperspb.StringValue {
	if m != nil {
		return m.Md5
	}
	return nil
}

func (m *ConfigFileReleaseHistory) GetType() *wrapperspb.StringValue {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *ConfigFileReleaseHistory) GetStatus() *wrapperspb.StringValue {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ConfigFileReleaseHistory) GetTags() []*ConfigFileTag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *ConfigFileReleaseHistory) GetCreateTime() *wrapperspb.StringValue {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *ConfigFileReleaseHistory) GetCreateBy() *wrapperspb.StringValue {
	if m != nil {
		return m.CreateBy
	}
	return nil
}

func (m *ConfigFileReleaseHistory) GetModifyTime() *wrapperspb.StringValue {
	if m != nil {
		return m.ModifyTime
	}
	return nil
}

func (m *ConfigFileReleaseHistory) GetModifyBy() *wrapperspb.StringValue {
	if m != nil {
		return m.ModifyBy
	}
	return nil
}

func (m *ConfigFileReleaseHistory) GetReason() *wrapperspb.StringValue {
	if m != nil {
		return m.Reason
	}
	return nil
}

func (m *ConfigFileReleaseHistory) GetReleaseDescription() *wrapperspb.StringValue {
	if m != nil {
		return m.ReleaseDescription
	}
	return nil
}

type ConfigFileTemplate struct {
	Id                   *wrapperspb.UInt64Value `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Content              *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Format               *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	Comment              *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	CreateTime           *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	CreateBy             *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=create_by,json=createBy,proto3" json:"create_by,omitempty"`
	ModifyTime           *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=modify_time,json=modifyTime,proto3" json:"modify_time,omitempty"`
	ModifyBy             *wrapperspb.StringValue `protobuf:"bytes,9,opt,name=modify_by,json=modifyBy,proto3" json:"modify_by,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ConfigFileTemplate) Reset()         { *m = ConfigFileTemplate{} }
func (m *ConfigFileTemplate) String() string { return proto.CompactTextString(m) }
func (*ConfigFileTemplate) ProtoMessage()    {}
func (*ConfigFileTemplate) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_file_72bb0a0c8382e743, []int{5}
}
func (m *ConfigFileTemplate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigFileTemplate.Unmarshal(m, b)
}
func (m *ConfigFileTemplate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigFileTemplate.Marshal(b, m, deterministic)
}
func (dst *ConfigFileTemplate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigFileTemplate.Merge(dst, src)
}
func (m *ConfigFileTemplate) XXX_Size() int {
	return xxx_messageInfo_ConfigFileTemplate.Size(m)
}
func (m *ConfigFileTemplate) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigFileTemplate.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigFileTemplate proto.InternalMessageInfo

func (m *ConfigFileTemplate) GetId() *wrapperspb.UInt64Value {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ConfigFileTemplate) GetName() *wrapperspb.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *ConfigFileTemplate) GetContent() *wrapperspb.StringValue {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *ConfigFileTemplate) GetFormat() *wrapperspb.StringValue {
	if m != nil {
		return m.Format
	}
	return nil
}

func (m *ConfigFileTemplate) GetComment() *wrapperspb.StringValue {
	if m != nil {
		return m.Comment
	}
	return nil
}

func (m *ConfigFileTemplate) GetCreateTime() *wrapperspb.StringValue {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *ConfigFileTemplate) GetCreateBy() *wrapperspb.StringValue {
	if m != nil {
		return m.CreateBy
	}
	return nil
}

func (m *ConfigFileTemplate) GetModifyTime() *wrapperspb.StringValue {
	if m != nil {
		return m.ModifyTime
	}
	return nil
}

func (m *ConfigFileTemplate) GetModifyBy() *wrapperspb.StringValue {
	if m != nil {
		return m.ModifyBy
	}
	return nil
}

type ClientConfigFileInfo struct {
	Namespace *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Group     *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	FileName  *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Content   *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Version   *wrapperspb.UInt64Value `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Md5       *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=md5,proto3" json:"md5,omitempty"`
	Tags      []*ConfigFileTag        `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	// 是否为加密配置文件
	Encrypted *wrapperspb.BoolValue `protobuf:"bytes,8,opt,name=encrypted,proto3" json:"encrypted,omitempty"`
	// 公钥，用于加密数据密钥
	PublicKey *wrapperspb.StringValue `protobuf:"bytes,9,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// 配置文件版本名称
	Name *wrapperspb.StringValue `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	// 配置文件的发布时间
	ReleaseTime          *wrapperspb.StringValue `protobuf:"bytes,11,opt,name=release_time,proto3" json:"release_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ClientConfigFileInfo) Reset()         { *m = ClientConfigFileInfo{} }
func (m *ClientConfigFileInfo) String() string { return proto.CompactTextString(m) }
func (*ClientConfigFileInfo) ProtoMessage()    {}
func (*ClientConfigFileInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_file_72bb0a0c8382e743, []int{6}
}
func (m *ClientConfigFileInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientConfigFileInfo.Unmarshal(m, b)
}
func (m *ClientConfigFileInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientConfigFileInfo.Marshal(b, m, deterministic)
}
func (dst *ClientConfigFileInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientConfigFileInfo.Merge(dst, src)
}
func (m *ClientConfigFileInfo) XXX_Size() int {
	return xxx_messageInfo_ClientConfigFileInfo.Size(m)
}
func (m *ClientConfigFileInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientConfigFileInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClientConfigFileInfo proto.InternalMessageInfo

func (m *ClientConfigFileInfo) GetNamespace() *wrapperspb.StringValue {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *ClientConfigFileInfo) GetGroup() *wrapperspb.StringValue {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *ClientConfigFileInfo) GetFileName() *wrapperspb.StringValue {
	if m != nil {
		return m.FileName
	}
	return nil
}

func (m *ClientConfigFileInfo) GetContent() *wrapperspb.StringValue {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *ClientConfigFileInfo) GetVersion() *wrapperspb.UInt64Value {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *ClientConfigFileInfo) GetMd5() *wrapperspb.StringValue {
	if m != nil {
		return m.Md5
	}
	return nil
}

func (m *ClientConfigFileInfo) GetTags() []*ConfigFileTag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *ClientConfigFileInfo) GetEncrypted() *wrapperspb.BoolValue {
	if m != nil {
		return m.Encrypted
	}
	return nil
}

func (m *ClientConfigFileInfo) GetPublicKey() *wrapperspb.StringValue {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *ClientConfigFileInfo) GetName() *wrapperspb.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *ClientConfigFileInfo) GetReleaseTime() *wrapperspb.StringValue {
	if m != nil {
		return m.ReleaseTime
	}
	return nil
}

type ClientWatchConfigFileRequest struct {
	ClientIp             *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	ServiceName          *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	WatchFiles           []*ClientConfigFileInfo `protobuf:"bytes,3,rep,name=watch_files,json=watchFiles,proto3" json:"watch_files,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ClientWatchConfigFileRequest) Reset()         { *m = ClientWatchConfigFileRequest{} }
func (m *ClientWatchConfigFileRequest) String() string { return proto.CompactTextString(m) }
func (*ClientWatchConfigFileRequest) ProtoMessage()    {}
func (*ClientWatchConfigFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_file_72bb0a0c8382e743, []int{7}
}
func (m *ClientWatchConfigFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientWatchConfigFileRequest.Unmarshal(m, b)
}
func (m *ClientWatchConfigFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientWatchConfigFileRequest.Marshal(b, m, deterministic)
}
func (dst *ClientWatchConfigFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientWatchConfigFileRequest.Merge(dst, src)
}
func (m *ClientWatchConfigFileRequest) XXX_Size() int {
	return xxx_messageInfo_ClientWatchConfigFileRequest.Size(m)
}
func (m *ClientWatchConfigFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientWatchConfigFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClientWatchConfigFileRequest proto.InternalMessageInfo

func (m *ClientWatchConfigFileRequest) GetClientIp() *wrapperspb.StringValue {
	if m != nil {
		return m.ClientIp
	}
	return nil
}

func (m *ClientWatchConfigFileRequest) GetServiceName() *wrapperspb.StringValue {
	if m != nil {
		return m.ServiceName
	}
	return nil
}

func (m *ClientWatchConfigFileRequest) GetWatchFiles() []*ClientConfigFileInfo {
	if m != nil {
		return m.WatchFiles
	}
	return nil
}

type ConfigFileExportRequest struct {
	Namespace            *wrapperspb.StringValue   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Groups               []*wrapperspb.StringValue `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	Names                []*wrapperspb.StringValue `protobuf:"bytes,3,rep,name=names,proto3" json:"names,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ConfigFileExportRequest) Reset()         { *m = ConfigFileExportRequest{} }
func (m *ConfigFileExportRequest) String() string { return proto.CompactTextString(m) }
func (*ConfigFileExportRequest) ProtoMessage()    {}
func (*ConfigFileExportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_file_72bb0a0c8382e743, []int{8}
}
func (m *ConfigFileExportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigFileExportRequest.Unmarshal(m, b)
}
func (m *ConfigFileExportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigFileExportRequest.Marshal(b, m, deterministic)
}
func (dst *ConfigFileExportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigFileExportRequest.Merge(dst, src)
}
func (m *ConfigFileExportRequest) XXX_Size() int {
	return xxx_messageInfo_ConfigFileExportRequest.Size(m)
}
func (m *ConfigFileExportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigFileExportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigFileExportRequest proto.InternalMessageInfo

func (m *ConfigFileExportRequest) GetNamespace() *wrapperspb.StringValue {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *ConfigFileExportRequest) GetGroups() []*wrapperspb.StringValue {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *ConfigFileExportRequest) GetNames() []*wrapperspb.StringValue {
	if m != nil {
		return m.Names
	}
	return nil
}

type ConfigFilePublishInfo struct {
	ReleaseName          *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=release_name,proto3" json:"release_name,omitempty"`
	Namespace            *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Group                *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	FileName             *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=file_name,proto3" json:"file_name,omitempty"`
	Content              *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Comment              *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=comment,proto3" json:"comment,omitempty"`
	Format               *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=format,proto3" json:"format,omitempty"`
	ReleaseDescription   *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=release_description,proto3" json:"release_description,omitempty"`
	CreateBy             *wrapperspb.StringValue `protobuf:"bytes,11,opt,name=create_by,proto3" json:"create_by,omitempty"`
	ModifyBy             *wrapperspb.StringValue `protobuf:"bytes,13,opt,name=modify_by,proto3" json:"modify_by,omitempty"`
	Tags                 []*ConfigFileTag        `protobuf:"bytes,14,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ConfigFilePublishInfo) Reset()         { *m = ConfigFilePublishInfo{} }
func (m *ConfigFilePublishInfo) String() string { return proto.CompactTextString(m) }
func (*ConfigFilePublishInfo) ProtoMessage()    {}
func (*ConfigFilePublishInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_file_72bb0a0c8382e743, []int{9}
}
func (m *ConfigFilePublishInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigFilePublishInfo.Unmarshal(m, b)
}
func (m *ConfigFilePublishInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigFilePublishInfo.Marshal(b, m, deterministic)
}
func (dst *ConfigFilePublishInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigFilePublishInfo.Merge(dst, src)
}
func (m *ConfigFilePublishInfo) XXX_Size() int {
	return xxx_messageInfo_ConfigFilePublishInfo.Size(m)
}
func (m *ConfigFilePublishInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigFilePublishInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigFilePublishInfo proto.InternalMessageInfo

func (m *ConfigFilePublishInfo) GetReleaseName() *wrapperspb.StringValue {
	if m != nil {
		return m.ReleaseName
	}
	return nil
}

func (m *ConfigFilePublishInfo) GetNamespace() *wrapperspb.StringValue {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *ConfigFilePublishInfo) GetGroup() *wrapperspb.StringValue {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *ConfigFilePublishInfo) GetFileName() *wrapperspb.StringValue {
	if m != nil {
		return m.FileName
	}
	return nil
}

func (m *ConfigFilePublishInfo) GetContent() *wrapperspb.StringValue {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *ConfigFilePublishInfo) GetComment() *wrapperspb.StringValue {
	if m != nil {
		return m.Comment
	}
	return nil
}

func (m *ConfigFilePublishInfo) GetFormat() *wrapperspb.StringValue {
	if m != nil {
		return m.Format
	}
	return nil
}

func (m *ConfigFilePublishInfo) GetReleaseDescription() *wrapperspb.StringValue {
	if m != nil {
		return m.ReleaseDescription
	}
	return nil
}

func (m *ConfigFilePublishInfo) GetCreateBy() *wrapperspb.StringValue {
	if m != nil {
		return m.CreateBy
	}
	return nil
}

func (m *ConfigFilePublishInfo) GetModifyBy() *wrapperspb.StringValue {
	if m != nil {
		return m.ModifyBy
	}
	return nil
}

func (m *ConfigFilePublishInfo) GetTags() []*ConfigFileTag {
	if m != nil {
		return m.Tags
	}
	return nil
}

type ConfigFileGroupRequest struct {
	Revision             *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=revision,proto3" json:"revision,omitempty"`
	ConfigFileGroup      *ConfigFileGroup        `protobuf:"bytes,2,opt,name=config_file_group,json=configFileGroup,proto3" json:"config_file_group,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ConfigFileGroupRequest) Reset()         { *m = ConfigFileGroupRequest{} }
func (m *ConfigFileGroupRequest) String() string { return proto.CompactTextString(m) }
func (*ConfigFileGroupRequest) ProtoMessage()    {}
func (*ConfigFileGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_file_72bb0a0c8382e743, []int{10}
}
func (m *ConfigFileGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigFileGroupRequest.Unmarshal(m, b)
}
func (m *ConfigFileGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigFileGroupRequest.Marshal(b, m, deterministic)
}
func (dst *ConfigFileGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigFileGroupRequest.Merge(dst, src)
}
func (m *ConfigFileGroupRequest) XXX_Size() int {
	return xxx_messageInfo_ConfigFileGroupRequest.Size(m)
}
func (m *ConfigFileGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigFileGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigFileGroupRequest proto.InternalMessageInfo

func (m *ConfigFileGroupRequest) GetRevision() *wrapperspb.StringValue {
	if m != nil {
		return m.Revision
	}
	return nil
}

func (m *ConfigFileGroupRequest) GetConfigFileGroup() *ConfigFileGroup {
	if m != nil {
		return m.ConfigFileGroup
	}
	return nil
}

func init() {
	proto.RegisterType((*ConfigFileGroup)(nil), "v1.ConfigFileGroup")
	proto.RegisterMapType((map[string]string)(nil), "v1.ConfigFileGroup.MetadataEntry")
	proto.RegisterType((*ConfigFile)(nil), "v1.ConfigFile")
	proto.RegisterType((*ConfigFileTag)(nil), "v1.ConfigFileTag")
	proto.RegisterType((*ConfigFileRelease)(nil), "v1.ConfigFileRelease")
	proto.RegisterType((*ConfigFileReleaseHistory)(nil), "v1.ConfigFileReleaseHistory")
	proto.RegisterType((*ConfigFileTemplate)(nil), "v1.ConfigFileTemplate")
	proto.RegisterType((*ClientConfigFileInfo)(nil), "v1.ClientConfigFileInfo")
	proto.RegisterType((*ClientWatchConfigFileRequest)(nil), "v1.ClientWatchConfigFileRequest")
	proto.RegisterType((*ConfigFileExportRequest)(nil), "v1.ConfigFileExportRequest")
	proto.RegisterType((*ConfigFilePublishInfo)(nil), "v1.ConfigFilePublishInfo")
	proto.RegisterType((*ConfigFileGroupRequest)(nil), "v1.ConfigFileGroupRequest")
}

func init() { proto.RegisterFile("config_file.proto", fileDescriptor_config_file_72bb0a0c8382e743) }

var fileDescriptor_config_file_72bb0a0c8382e743 = []byte{
	// 1280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x99, 0x5d, 0x6f, 0xdc, 0x44,
	0x17, 0xc7, 0xb5, 0xef, 0xde, 0xb3, 0xcd, 0xdb, 0xb4, 0xcf, 0x83, 0x55, 0x55, 0xa8, 0xac, 0x84,
	0xc4, 0x05, 0xf2, 0xb6, 0x21, 0x44, 0x69, 0x43, 0x55, 0xd8, 0xd0, 0xd2, 0x08, 0xb5, 0xaa, 0x96,
	0x02, 0x12, 0x37, 0xab, 0x59, 0xef, 0xac, 0x33, 0xc2, 0xf6, 0x18, 0xcf, 0xec, 0x06, 0x5f, 0x73,
	0xdf, 0x1b, 0xee, 0xf8, 0x32, 0xdc, 0x23, 0x6e, 0xf9, 0x24, 0x5c, 0x23, 0xa1, 0x19, 0x8f, 0x63,
	0x6f, 0x92, 0x26, 0x63, 0x5b, 0x48, 0x08, 0xb8, 0x4a, 0x76, 0xfd, 0x3f, 0xe7, 0x78, 0x66, 0xce,
	0xf9, 0xcd, 0x99, 0x59, 0xd8, 0x71, 0x59, 0xb8, 0xa0, 0xde, 0x74, 0x41, 0x7d, 0xe2, 0x44, 0x31,
	0x13, 0x0c, 0x35, 0x57, 0xf7, 0x6f, 0xbf, 0xed, 0x31, 0xe6, 0xf9, 0x64, 0xa4, 0xbe, 0x99, 0x2d,
	0x17, 0xa3, 0xd3, 0x18, 0x47, 0x11, 0x89, 0x79, 0xaa, 0x19, 0xfe, 0x61, 0xc1, 0xd6, 0x91, 0xb2,
	0x7c, 0x4a, 0x7d, 0xf2, 0x59, 0xcc, 0x96, 0x11, 0x7a, 0x1f, 0x9a, 0x74, 0x6e, 0x37, 0xee, 0x36,
	0xde, 0x1b, 0xec, 0xde, 0x71, 0x52, 0x07, 0x4e, 0xe6, 0xc0, 0xf9, 0xf2, 0x38, 0x14, 0xfb, 0x7b,
	0x5f, 0x61, 0x7f, 0x49, 0x26, 0x4d, 0x3a, 0x47, 0xf7, 0xa0, 0x1d, 0xe2, 0x80, 0xd8, 0xcd, 0x37,
	0xe8, 0xbf, 0x10, 0x31, 0x0d, 0xbd, 0x54, 0xaf, 0x94, 0xe8, 0x21, 0xf4, 0xe5, 0x5f, 0x1e, 0x61,
	0x97, 0xd8, 0x2d, 0x03, 0xb3, 0x5c, 0x8e, 0xf6, 0xa1, 0xe7, 0xb2, 0x20, 0x20, 0xa1, 0xb0, 0xdb,
	0x06, 0x96, 0x99, 0x18, 0x3d, 0x82, 0x81, 0x1b, 0x13, 0x2c, 0xc8, 0x54, 0xd0, 0x80, 0xd8, 0x1d,
	0x03, 0x5b, 0x48, 0x0d, 0x5e, 0xd1, 0x80, 0xa0, 0x07, 0xd0, 0xd7, 0xe6, 0xb3, 0xc4, 0xee, 0x1a,
	0x18, 0x5b, 0xa9, 0x7c, 0x9c, 0xc8, 0xc8, 0x01, 0x9b, 0xd3, 0x45, 0x92, 0x46, 0xee, 0x99, 0x44,
	0x4e, 0x0d, 0xb2, 0xc8, 0xda, 0x7c, 0x96, 0xd8, 0x96, 0x49, 0xe4, 0x54, 0x3e, 0x4e, 0xe4, 0x3c,
	0xcb, 0x6c, 0x38, 0x62, 0xcb, 0x50, 0xd8, 0x7d, 0x83, 0xe5, 0xcc, 0xe5, 0xe8, 0x00, 0xac, 0x25,
	0x27, 0xf1, 0x94, 0xce, 0xb9, 0x0d, 0x77, 0x5b, 0xd7, 0x47, 0xcd, 0xd4, 0x32, 0xaa, 0x27, 0xd3,
	0x48, 0x99, 0x0e, 0x0c, 0x4c, 0x73, 0x39, 0x7a, 0x0a, 0x5b, 0x31, 0x09, 0xd8, 0x8a, 0x4c, 0xcf,
	0x82, 0x6f, 0x18, 0x78, 0x38, 0x6f, 0x84, 0x9e, 0xc1, 0xb6, 0xfe, 0x2a, 0x7f, 0x95, 0x4d, 0x03,
	0x47, 0x17, 0xac, 0xd0, 0x3e, 0x58, 0x64, 0x4e, 0x05, 0x9e, 0xf9, 0xc4, 0xde, 0x52, 0x53, 0x78,
	0xfb, 0x82, 0x87, 0x31, 0x63, 0xbe, 0x9e, 0x85, 0x4c, 0x8b, 0x76, 0xa1, 0xc3, 0x4e, 0x43, 0x12,
	0xdb, 0xdb, 0x06, 0x4b, 0x96, 0x4a, 0xe5, 0x9c, 0xcf, 0x96, 0x9c, 0x86, 0x84, 0x73, 0x7b, 0xc7,
	0x64, 0xa5, 0x33, 0x35, 0xfa, 0x08, 0x60, 0x4e, 0x22, 0x1c, 0x0b, 0x55, 0x18, 0xc8, 0x24, 0xc5,
	0x72, 0x3d, 0x7a, 0x04, 0x56, 0x40, 0x04, 0x9e, 0x63, 0x81, 0xed, 0x9b, 0x6a, 0x96, 0xde, 0x71,
	0x56, 0xf7, 0x9d, 0x73, 0x58, 0x70, 0x9e, 0x6b, 0xcd, 0x93, 0x50, 0xc4, 0xc9, 0xe4, 0xcc, 0xe4,
	0xf6, 0x21, 0x6c, 0xac, 0x3d, 0x42, 0xdb, 0xd0, 0xfa, 0x96, 0x24, 0x0a, 0x20, 0xfd, 0x89, 0xfc,
	0x17, 0xdd, 0x82, 0xce, 0x4a, 0x86, 0x55, 0x90, 0xe8, 0x4f, 0xd2, 0x0f, 0x0f, 0x9b, 0x07, 0x8d,
	0xe1, 0xaf, 0x3d, 0x80, 0x3c, 0xd0, 0xdf, 0x1a, 0x3d, 0xbb, 0xd0, 0x51, 0x79, 0x61, 0x04, 0x9e,
	0x54, 0x9a, 0xe2, 0x2a, 0x14, 0x72, 0x55, 0x3a, 0x66, 0xb8, 0x52, 0x62, 0xb4, 0x07, 0xdd, 0x05,
	0x8b, 0x03, 0x2c, 0x8c, 0x60, 0xa3, 0xb5, 0x45, 0x38, 0xf6, 0xca, 0xc0, 0x71, 0x0f, 0xba, 0x5c,
	0x60, 0xb1, 0xe4, 0x46, 0x80, 0xd1, 0x5a, 0xf4, 0x2e, 0xb4, 0x05, 0xf6, 0xb8, 0xdd, 0x57, 0x29,
	0xb3, 0xb3, 0x9e, 0x32, 0xaf, 0xb0, 0x37, 0x51, 0x8f, 0xcf, 0x93, 0x17, 0xea, 0x90, 0x77, 0x50,
	0x87, 0xbc, 0x37, 0xea, 0x90, 0x77, 0xa3, 0x14, 0x79, 0x1f, 0xc3, 0x8d, 0x98, 0xf8, 0x04, 0x73,
	0x3d, 0xe8, 0x4d, 0x03, 0xeb, 0x81, 0xb6, 0x50, 0xb1, 0x0f, 0x01, 0x32, 0x07, 0xb3, 0x44, 0x83,
	0xe7, 0x9a, 0x44, 0xd5, 0xfa, 0x71, 0x82, 0x0e, 0xa0, 0x4f, 0x42, 0x37, 0x4e, 0x22, 0x41, 0xe6,
	0x9a, 0x3f, 0x57, 0x41, 0x2b, 0x17, 0xcb, 0xf7, 0xd6, 0x1f, 0xa6, 0xd8, 0xf7, 0x98, 0x11, 0x85,
	0x06, 0xda, 0xe2, 0x13, 0xdf, 0x63, 0x43, 0x0e, 0x1b, 0x6b, 0x39, 0x80, 0x9c, 0x9c, 0x05, 0xd7,
	0x39, 0x52, 0xa4, 0xd8, 0x2d, 0x92, 0xe2, 0xda, 0x22, 0x53, 0xd2, 0xe1, 0x2f, 0x3d, 0xd8, 0xc9,
	0xa3, 0x4e, 0xd2, 0x79, 0xf8, 0xc7, 0xa1, 0xe4, 0x41, 0xba, 0x9b, 0x4f, 0xd5, 0x6b, 0x9a, 0xc0,
	0xc4, 0x92, 0xf2, 0x17, 0xf2, 0x55, 0x0b, 0x14, 0xea, 0x96, 0xa1, 0x50, 0x55, 0x9e, 0x38, 0xd0,
	0x0a, 0xe6, 0x1f, 0x1a, 0xc1, 0x44, 0x0a, 0x65, 0x9c, 0x15, 0x89, 0x39, 0x65, 0xa1, 0x51, 0x9b,
	0x92, 0x89, 0xff, 0x95, 0x68, 0xc9, 0xa8, 0xbb, 0x79, 0x35, 0x75, 0x77, 0xa1, 0x8b, 0x5d, 0x41,
	0x57, 0x26, 0x5d, 0x8b, 0x56, 0x16, 0x36, 0x9d, 0xed, 0x12, 0x9b, 0xce, 0x73, 0xb8, 0x99, 0xa1,
	0x6a, 0x4e, 0xb8, 0x1b, 0xd3, 0x48, 0xc8, 0x85, 0x34, 0x41, 0x07, 0xd2, 0x86, 0x9f, 0xe6, 0x76,
	0xc3, 0x1f, 0x2c, 0xb0, 0x2f, 0x14, 0xf3, 0x33, 0xca, 0x05, 0x8b, 0x93, 0xff, 0x6a, 0xba, 0x7e,
	0x4d, 0xe7, 0x8b, 0xdc, 0xab, 0xd6, 0x59, 0x58, 0x15, 0x48, 0xd0, 0x37, 0x25, 0xc1, 0x3d, 0x68,
	0x8b, 0x24, 0x32, 0x2b, 0x65, 0xa5, 0x2c, 0xf4, 0x2e, 0x83, 0x0a, 0xbd, 0xcb, 0x8d, 0x52, 0xbd,
	0xcb, 0x46, 0x1d, 0xc0, 0x6c, 0xd6, 0x01, 0xcc, 0x56, 0x1d, 0xc0, 0x6c, 0x97, 0x02, 0xcc, 0x1e,
	0x74, 0x63, 0x82, 0xb9, 0x61, 0x09, 0x6b, 0xed, 0x9b, 0x28, 0x80, 0x2a, 0x52, 0xe0, 0x75, 0x1b,
	0x50, 0x61, 0x41, 0x48, 0x10, 0xf9, 0x58, 0xfc, 0xf5, 0x7b, 0x7a, 0xa1, 0xa8, 0x5a, 0xd5, 0x8a,
	0xaa, 0x5d, 0xad, 0xa8, 0x3a, 0x35, 0xee, 0x32, 0xba, 0x75, 0xb2, 0xb2, 0x57, 0x27, 0x2b, 0xad,
	0x3a, 0x59, 0xd9, 0x2f, 0x93, 0x95, 0xc3, 0xdf, 0xdb, 0x70, 0xeb, 0xc8, 0xa7, 0x24, 0x14, 0x79,
	0x5a, 0x1c, 0x87, 0x0b, 0xb6, 0x8e, 0xec, 0x46, 0x45, 0x64, 0x37, 0x2b, 0x22, 0xbb, 0x55, 0x15,
	0xd9, 0xed, 0x92, 0x6d, 0x58, 0xd6, 0x1e, 0x75, 0xca, 0xb4, 0x47, 0x1a, 0xbe, 0x5d, 0x53, 0xf8,
	0x66, 0x50, 0xec, 0x5d, 0x0d, 0xc5, 0xb5, 0xe3, 0x85, 0x55, 0xe6, 0x78, 0x71, 0x08, 0x10, 0x2d,
	0x67, 0x3e, 0x75, 0xa7, 0xf2, 0x4c, 0x60, 0x92, 0x00, 0xfd, 0x54, 0xff, 0x39, 0x49, 0xce, 0xaa,
	0x19, 0x8c, 0xab, 0xf9, 0xe3, 0x73, 0xa7, 0x30, 0x93, 0x0d, 0x62, 0xcd, 0x62, 0xf8, 0x5b, 0x03,
	0xee, 0xa4, 0x59, 0xf7, 0x35, 0x16, 0xee, 0x49, 0xb1, 0x2f, 0xf9, 0x6e, 0x49, 0xb8, 0x50, 0xb5,
	0xa4, 0x9e, 0x4f, 0x69, 0x64, 0x94, 0x7d, 0x56, 0x2a, 0x3f, 0x8e, 0xe4, 0x59, 0x8b, 0x93, 0x78,
	0x45, 0x5d, 0x9d, 0x4b, 0x26, 0x39, 0x38, 0xd0, 0x16, 0x2a, 0x9d, 0x1e, 0xc0, 0xe0, 0x54, 0xbe,
	0x95, 0xba, 0xf2, 0xe5, 0x76, 0x4b, 0xad, 0x9a, 0xad, 0x56, 0xed, 0x92, 0x42, 0x99, 0x80, 0x12,
	0xcb, 0x8f, 0x7c, 0xf8, 0x73, 0x03, 0xde, 0xca, 0x1f, 0x3f, 0xf9, 0x3e, 0x62, 0xb1, 0xc8, 0x86,
	0x54, 0xa7, 0xa0, 0xf6, 0xa0, 0xab, 0xaa, 0x84, 0xdb, 0x4d, 0x83, 0xdb, 0x36, 0xad, 0x95, 0x65,
	0xa8, 0x5c, 0xe8, 0x21, 0x5c, 0x53, 0x86, 0x4a, 0x3a, 0xfc, 0xa9, 0x03, 0xff, 0xcb, 0x47, 0xf0,
	0x52, 0x66, 0x09, 0x3f, 0x51, 0x40, 0x28, 0xac, 0xba, 0x9a, 0xd7, 0x46, 0x99, 0x55, 0xbf, 0xd8,
	0x05, 0x36, 0x2b, 0x22, 0xa5, 0x65, 0x8e, 0x94, 0x87, 0x45, 0xa4, 0x98, 0x90, 0x21, 0x97, 0x57,
	0xbe, 0x60, 0x2a, 0xec, 0x3d, 0xdd, 0x92, 0x57, 0x45, 0x15, 0xda, 0xc7, 0x17, 0x97, 0x77, 0x07,
	0x26, 0xfb, 0xc7, 0x65, 0x86, 0x72, 0xc6, 0xca, 0x9d, 0xdc, 0x72, 0xb9, 0xb4, 0x2d, 0x77, 0xf6,
	0xca, 0xe5, 0x86, 0x87, 0xaf, 0xe1, 0x8f, 0x0d, 0xf8, 0xff, 0xb9, 0xdb, 0xd3, 0xac, 0xba, 0x0e,
	0xc0, 0x8a, 0xc9, 0x8a, 0x2a, 0x98, 0x1b, 0xf1, 0x22, 0x53, 0xa3, 0xc7, 0x6b, 0x3f, 0xf1, 0x4c,
	0x8b, 0x1b, 0xd7, 0xcd, 0x4b, 0xae, 0x6b, 0x27, 0x5b, 0xee, 0xfa, 0x17, 0xe3, 0xd7, 0x0d, 0xd8,
	0x77, 0x59, 0xe0, 0x08, 0x12, 0xba, 0x24, 0x14, 0x4e, 0xc4, 0x7c, 0x1c, 0x53, 0xee, 0xf0, 0x88,
	0xb8, 0x74, 0x41, 0x5d, 0x2c, 0xa7, 0xd6, 0xc1, 0x11, 0x95, 0xde, 0x52, 0x63, 0x27, 0xc0, 0x21,
	0xf6, 0xc8, 0xb8, 0xf0, 0x13, 0xd1, 0x4b, 0xf9, 0x96, 0xdf, 0x1c, 0x79, 0x54, 0x9c, 0x2c, 0x67,
	0x8e, 0xcb, 0x82, 0x91, 0xf6, 0x13, 0x10, 0x7e, 0x32, 0x5a, 0xf3, 0x35, 0xe2, 0x6c, 0x19, 0xbb,
	0x64, 0xe4, 0xb1, 0x11, 0x8e, 0xe8, 0x68, 0x75, 0x7f, 0xa4, 0x07, 0x90, 0x7a, 0x9d, 0x75, 0xd5,
	0x88, 0x3f, 0xf8, 0x33, 0x00, 0x00, 0xff, 0xff, 0x3c, 0x9a, 0x0a, 0x52, 0xbb, 0x1a, 0x00, 0x00,
}
