// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc_config_api.proto

package config_manage // import "github.com/polarismesh/specification/source/go/api/v1/config_manage"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PolarisConfigGRPCClient is the client API for PolarisConfigGRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PolarisConfigGRPCClient interface {
	// 拉取配置
	GetConfigFile(ctx context.Context, in *ClientConfigFileInfo, opts ...grpc.CallOption) (*ConfigClientResponse, error)
	// 创建配置
	CreateConfigFile(ctx context.Context, in *ConfigFile, opts ...grpc.CallOption) (*ConfigClientResponse, error)
	// 更新配置
	UpdateConfigFile(ctx context.Context, in *ConfigFile, opts ...grpc.CallOption) (*ConfigClientResponse, error)
	// 发布配置
	PublishConfigFile(ctx context.Context, in *ConfigFileRelease, opts ...grpc.CallOption) (*ConfigClientResponse, error)
	// 订阅配置变更
	WatchConfigFiles(ctx context.Context, in *ClientWatchConfigFileRequest, opts ...grpc.CallOption) (*ConfigClientResponse, error)
	// 拉取指定配置分组下的配置文件列表
	GetConfigFileMetadataList(ctx context.Context, in *ConfigFileGroupRequest, opts ...grpc.CallOption) (*ConfigClientListResponse, error)
}

type polarisConfigGRPCClient struct {
	cc *grpc.ClientConn
}

func NewPolarisConfigGRPCClient(cc *grpc.ClientConn) PolarisConfigGRPCClient {
	return &polarisConfigGRPCClient{cc}
}

func (c *polarisConfigGRPCClient) GetConfigFile(ctx context.Context, in *ClientConfigFileInfo, opts ...grpc.CallOption) (*ConfigClientResponse, error) {
	out := new(ConfigClientResponse)
	err := c.cc.Invoke(ctx, "/v1.PolarisConfigGRPC/GetConfigFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *polarisConfigGRPCClient) CreateConfigFile(ctx context.Context, in *ConfigFile, opts ...grpc.CallOption) (*ConfigClientResponse, error) {
	out := new(ConfigClientResponse)
	err := c.cc.Invoke(ctx, "/v1.PolarisConfigGRPC/CreateConfigFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *polarisConfigGRPCClient) UpdateConfigFile(ctx context.Context, in *ConfigFile, opts ...grpc.CallOption) (*ConfigClientResponse, error) {
	out := new(ConfigClientResponse)
	err := c.cc.Invoke(ctx, "/v1.PolarisConfigGRPC/UpdateConfigFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *polarisConfigGRPCClient) PublishConfigFile(ctx context.Context, in *ConfigFileRelease, opts ...grpc.CallOption) (*ConfigClientResponse, error) {
	out := new(ConfigClientResponse)
	err := c.cc.Invoke(ctx, "/v1.PolarisConfigGRPC/PublishConfigFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *polarisConfigGRPCClient) WatchConfigFiles(ctx context.Context, in *ClientWatchConfigFileRequest, opts ...grpc.CallOption) (*ConfigClientResponse, error) {
	out := new(ConfigClientResponse)
	err := c.cc.Invoke(ctx, "/v1.PolarisConfigGRPC/WatchConfigFiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *polarisConfigGRPCClient) GetConfigFileMetadataList(ctx context.Context, in *ConfigFileGroupRequest, opts ...grpc.CallOption) (*ConfigClientListResponse, error) {
	out := new(ConfigClientListResponse)
	err := c.cc.Invoke(ctx, "/v1.PolarisConfigGRPC/GetConfigFileMetadataList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PolarisConfigGRPCServer is the server API for PolarisConfigGRPC service.
type PolarisConfigGRPCServer interface {
	// 拉取配置
	GetConfigFile(context.Context, *ClientConfigFileInfo) (*ConfigClientResponse, error)
	// 创建配置
	CreateConfigFile(context.Context, *ConfigFile) (*ConfigClientResponse, error)
	// 更新配置
	UpdateConfigFile(context.Context, *ConfigFile) (*ConfigClientResponse, error)
	// 发布配置
	PublishConfigFile(context.Context, *ConfigFileRelease) (*ConfigClientResponse, error)
	// 订阅配置变更
	WatchConfigFiles(context.Context, *ClientWatchConfigFileRequest) (*ConfigClientResponse, error)
	// 拉取指定配置分组下的配置文件列表
	GetConfigFileMetadataList(context.Context, *ConfigFileGroupRequest) (*ConfigClientListResponse, error)
}

func RegisterPolarisConfigGRPCServer(s *grpc.Server, srv PolarisConfigGRPCServer) {
	s.RegisterService(&_PolarisConfigGRPC_serviceDesc, srv)
}

func _PolarisConfigGRPC_GetConfigFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientConfigFileInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolarisConfigGRPCServer).GetConfigFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.PolarisConfigGRPC/GetConfigFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolarisConfigGRPCServer).GetConfigFile(ctx, req.(*ClientConfigFileInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolarisConfigGRPC_CreateConfigFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigFile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolarisConfigGRPCServer).CreateConfigFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.PolarisConfigGRPC/CreateConfigFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolarisConfigGRPCServer).CreateConfigFile(ctx, req.(*ConfigFile))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolarisConfigGRPC_UpdateConfigFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigFile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolarisConfigGRPCServer).UpdateConfigFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.PolarisConfigGRPC/UpdateConfigFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolarisConfigGRPCServer).UpdateConfigFile(ctx, req.(*ConfigFile))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolarisConfigGRPC_PublishConfigFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigFileRelease)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolarisConfigGRPCServer).PublishConfigFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.PolarisConfigGRPC/PublishConfigFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolarisConfigGRPCServer).PublishConfigFile(ctx, req.(*ConfigFileRelease))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolarisConfigGRPC_WatchConfigFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientWatchConfigFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolarisConfigGRPCServer).WatchConfigFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.PolarisConfigGRPC/WatchConfigFiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolarisConfigGRPCServer).WatchConfigFiles(ctx, req.(*ClientWatchConfigFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolarisConfigGRPC_GetConfigFileMetadataList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigFileGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolarisConfigGRPCServer).GetConfigFileMetadataList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.PolarisConfigGRPC/GetConfigFileMetadataList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolarisConfigGRPCServer).GetConfigFileMetadataList(ctx, req.(*ConfigFileGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PolarisConfigGRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.PolarisConfigGRPC",
	HandlerType: (*PolarisConfigGRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfigFile",
			Handler:    _PolarisConfigGRPC_GetConfigFile_Handler,
		},
		{
			MethodName: "CreateConfigFile",
			Handler:    _PolarisConfigGRPC_CreateConfigFile_Handler,
		},
		{
			MethodName: "UpdateConfigFile",
			Handler:    _PolarisConfigGRPC_UpdateConfigFile_Handler,
		},
		{
			MethodName: "PublishConfigFile",
			Handler:    _PolarisConfigGRPC_PublishConfigFile_Handler,
		},
		{
			MethodName: "WatchConfigFiles",
			Handler:    _PolarisConfigGRPC_WatchConfigFiles_Handler,
		},
		{
			MethodName: "GetConfigFileMetadataList",
			Handler:    _PolarisConfigGRPC_GetConfigFileMetadataList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc_config_api.proto",
}

func init() {
	proto.RegisterFile("grpc_config_api.proto", fileDescriptor_grpc_config_api_598a4abdfad2fcf6)
}

var fileDescriptor_grpc_config_api_598a4abdfad2fcf6 = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xdf, 0x4a, 0xc3, 0x30,
	0x14, 0xc6, 0xfd, 0x03, 0x5e, 0x04, 0x94, 0xad, 0x30, 0x98, 0xc5, 0x0b, 0xf1, 0x01, 0x12, 0xaa,
	0xe0, 0xa5, 0x17, 0x2b, 0x6e, 0x08, 0x0a, 0xa5, 0x22, 0x03, 0x6f, 0x46, 0x96, 0x9d, 0x76, 0x07,
	0xd2, 0x24, 0x26, 0x69, 0x5f, 0xc5, 0xa7, 0xf2, 0x9d, 0x64, 0x4b, 0x65, 0xed, 0x84, 0x09, 0x5e,
	0xe6, 0xfb, 0xce, 0xf7, 0x4b, 0x38, 0xf9, 0xc8, 0xa8, 0xb4, 0x46, 0x2c, 0x84, 0x56, 0x05, 0x96,
	0x0b, 0x6e, 0x90, 0x1a, 0xab, 0xbd, 0x8e, 0x4e, 0x9a, 0x24, 0x1e, 0xb6, 0x6a, 0x81, 0x12, 0x82,
	0x1c, 0xc7, 0x1d, 0x69, 0x61, 0xc1, 0x19, 0xad, 0x5c, 0xeb, 0xdd, 0x7e, 0x9d, 0x92, 0x61, 0xa6,
	0x25, 0xb7, 0xe8, 0xd2, 0xed, 0xd4, 0x2c, 0xcf, 0xd2, 0xe8, 0x91, 0x9c, 0xcf, 0xc0, 0x07, 0x61,
	0x8a, 0x12, 0xa2, 0x31, 0x6d, 0x12, 0x9a, 0x4a, 0x04, 0xd5, 0x51, 0x9f, 0x54, 0xa1, 0xe3, 0xe0,
	0x6c, 0xb5, 0xe0, 0xe7, 0xed, 0x05, 0x37, 0x47, 0xd1, 0x03, 0x19, 0xa4, 0x16, 0xb8, 0x87, 0x0e,
	0xe9, 0x62, 0x37, 0xbf, 0x39, 0xff, 0x95, 0x7f, 0x33, 0xab, 0xff, 0xe7, 0xa7, 0x64, 0x98, 0xd5,
	0x4b, 0x89, 0x6e, 0xdd, 0x01, 0x8c, 0xfa, 0x80, 0x1c, 0x24, 0x70, 0x77, 0x98, 0x93, 0x91, 0xc1,
	0x9c, 0x7b, 0xd1, 0xa1, 0xb8, 0xe8, 0x7a, 0xb7, 0x91, 0x3d, 0x2f, 0x87, 0x8f, 0x1a, 0x9c, 0x3f,
	0x48, 0x9c, 0x93, 0xcb, 0xde, 0x82, 0x5f, 0xc0, 0xf3, 0x15, 0xf7, 0xfc, 0x19, 0x9d, 0x8f, 0xe2,
	0xfe, 0x0b, 0x67, 0x56, 0xd7, 0xe6, 0x07, 0x7a, 0xb5, 0x0f, 0xdd, 0x24, 0x76, 0xe0, 0xc9, 0xe7,
	0x31, 0xb9, 0x17, 0xba, 0xa2, 0x1e, 0x94, 0x00, 0xe5, 0xa9, 0x09, 0x7f, 0x4b, 0x9d, 0x01, 0x81,
	0x05, 0x0a, 0xee, 0x51, 0x2b, 0xba, 0xa9, 0x4c, 0x93, 0xd0, 0xd0, 0x0b, 0x5a, 0x71, 0xc5, 0x4b,
	0x98, 0x8c, 0x7f, 0xf5, 0xe0, 0x15, 0x6c, 0x83, 0x02, 0xde, 0xd3, 0x12, 0xfd, 0xba, 0x5e, 0x52,
	0xa1, 0x2b, 0xd6, 0x02, 0x2b, 0x70, 0x6b, 0xd6, 0x83, 0x32, 0xa7, 0x6b, 0x2b, 0x80, 0x95, 0x9a,
	0x71, 0x83, 0xac, 0x49, 0x58, 0x5b, 0xbb, 0x80, 0x5f, 0x9e, 0x6d, 0x0b, 0x77, 0xf7, 0x1d, 0x00,
	0x00, 0xff, 0xff, 0x8b, 0xd9, 0xe1, 0x52, 0xbc, 0x02, 0x00, 0x00,
}
