// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contract.proto

package service_manage // import "github.com/polarismesh/specification/source/go/api/v1/service_manage"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InterfaceDescriptor_Source int32

const (
	InterfaceDescriptor_UNKNOWN InterfaceDescriptor_Source = 0
	InterfaceDescriptor_Manual  InterfaceDescriptor_Source = 1
	InterfaceDescriptor_Client  InterfaceDescriptor_Source = 2
)

var InterfaceDescriptor_Source_name = map[int32]string{
	0: "UNKNOWN",
	1: "Manual",
	2: "Client",
}
var InterfaceDescriptor_Source_value = map[string]int32{
	"UNKNOWN": 0,
	"Manual":  1,
	"Client":  2,
}

func (x InterfaceDescriptor_Source) String() string {
	return proto.EnumName(InterfaceDescriptor_Source_name, int32(x))
}
func (InterfaceDescriptor_Source) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_contract_6b948cfbd95c06a7, []int{1, 0}
}

type ServiceContract struct {
	// 契约ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 契约名称
	// deprecated, use type field
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 所属命名空间
	Namespace string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// 所属服务名称
	Service string `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`
	// 协议，http/grpc/dubbo/thrift
	Protocol string `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// 契约版本
	Version string `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	// 信息摘要
	Revision string `protobuf:"bytes,7,opt,name=revision,proto3" json:"revision,omitempty"`
	// 额外描述
	Content string `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	// 接口描述信息
	Interfaces []*InterfaceDescriptor `protobuf:"bytes,9,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	// 创建时间
	Ctime string `protobuf:"bytes,10,opt,name=ctime,proto3" json:"ctime,omitempty"`
	// 更新时间
	Mtime string `protobuf:"bytes,11,opt,name=mtime,proto3" json:"mtime,omitempty"`
	// 接口状态，Offline/Online
	Status string `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	// 类型
	Type string `protobuf:"bytes,14,opt,name=type,proto3" json:"type,omitempty"`
	// 标签
	Metadata map[string]string `protobuf:"bytes,15,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// 内容摘要
	ContentDigest        string   `protobuf:"bytes,16,opt,name=content_digest,json=contentDigest,proto3" json:"content_digest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceContract) Reset()         { *m = ServiceContract{} }
func (m *ServiceContract) String() string { return proto.CompactTextString(m) }
func (*ServiceContract) ProtoMessage()    {}
func (*ServiceContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_contract_6b948cfbd95c06a7, []int{0}
}
func (m *ServiceContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceContract.Unmarshal(m, b)
}
func (m *ServiceContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceContract.Marshal(b, m, deterministic)
}
func (dst *ServiceContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceContract.Merge(dst, src)
}
func (m *ServiceContract) XXX_Size() int {
	return xxx_messageInfo_ServiceContract.Size(m)
}
func (m *ServiceContract) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceContract.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceContract proto.InternalMessageInfo

func (m *ServiceContract) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ServiceContract) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServiceContract) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ServiceContract) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *ServiceContract) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *ServiceContract) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ServiceContract) GetRevision() string {
	if m != nil {
		return m.Revision
	}
	return ""
}

func (m *ServiceContract) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ServiceContract) GetInterfaces() []*InterfaceDescriptor {
	if m != nil {
		return m.Interfaces
	}
	return nil
}

func (m *ServiceContract) GetCtime() string {
	if m != nil {
		return m.Ctime
	}
	return ""
}

func (m *ServiceContract) GetMtime() string {
	if m != nil {
		return m.Mtime
	}
	return ""
}

func (m *ServiceContract) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ServiceContract) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ServiceContract) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *ServiceContract) GetContentDigest() string {
	if m != nil {
		return m.ContentDigest
	}
	return ""
}

type InterfaceDescriptor struct {
	// 接口ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 方法名称，对应 http method/ dubbo interface func/grpc service func
	Method string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	// 接口名称，http path/dubbo interface/grpc service
	Path string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	// 接口描述信息
	Content string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	// 创建来源
	Source InterfaceDescriptor_Source `protobuf:"varint,5,opt,name=source,proto3,enum=v1.InterfaceDescriptor_Source" json:"source,omitempty"`
	// 接口信息摘要
	Revision string `protobuf:"bytes,6,opt,name=revision,proto3" json:"revision,omitempty"`
	// 创建时间
	Ctime string `protobuf:"bytes,7,opt,name=ctime,proto3" json:"ctime,omitempty"`
	// 更新时间
	Mtime string `protobuf:"bytes,8,opt,name=mtime,proto3" json:"mtime,omitempty"`
	// 接口名称描述信息
	// deprecated, use type field
	Name string `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
	// 所属命名空间
	Namespace string `protobuf:"bytes,10,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// 所属服务名称
	Service string `protobuf:"bytes,11,opt,name=service,proto3" json:"service,omitempty"`
	// 协议，http/grpc/dubbo/thrift
	Protocol string `protobuf:"bytes,12,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// 契约版本
	Version string `protobuf:"bytes,13,opt,name=version,proto3" json:"version,omitempty"`
	// 类型
	Type string `protobuf:"bytes,14,opt,name=type,proto3" json:"type,omitempty"`
	// 内容摘要
	ContentDigest        string   `protobuf:"bytes,15,opt,name=content_digest,json=contentDigest,proto3" json:"content_digest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InterfaceDescriptor) Reset()         { *m = InterfaceDescriptor{} }
func (m *InterfaceDescriptor) String() string { return proto.CompactTextString(m) }
func (*InterfaceDescriptor) ProtoMessage()    {}
func (*InterfaceDescriptor) Descriptor() ([]byte, []int) {
	return fileDescriptor_contract_6b948cfbd95c06a7, []int{1}
}
func (m *InterfaceDescriptor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InterfaceDescriptor.Unmarshal(m, b)
}
func (m *InterfaceDescriptor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InterfaceDescriptor.Marshal(b, m, deterministic)
}
func (dst *InterfaceDescriptor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterfaceDescriptor.Merge(dst, src)
}
func (m *InterfaceDescriptor) XXX_Size() int {
	return xxx_messageInfo_InterfaceDescriptor.Size(m)
}
func (m *InterfaceDescriptor) XXX_DiscardUnknown() {
	xxx_messageInfo_InterfaceDescriptor.DiscardUnknown(m)
}

var xxx_messageInfo_InterfaceDescriptor proto.InternalMessageInfo

func (m *InterfaceDescriptor) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *InterfaceDescriptor) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *InterfaceDescriptor) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *InterfaceDescriptor) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *InterfaceDescriptor) GetSource() InterfaceDescriptor_Source {
	if m != nil {
		return m.Source
	}
	return InterfaceDescriptor_UNKNOWN
}

func (m *InterfaceDescriptor) GetRevision() string {
	if m != nil {
		return m.Revision
	}
	return ""
}

func (m *InterfaceDescriptor) GetCtime() string {
	if m != nil {
		return m.Ctime
	}
	return ""
}

func (m *InterfaceDescriptor) GetMtime() string {
	if m != nil {
		return m.Mtime
	}
	return ""
}

func (m *InterfaceDescriptor) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InterfaceDescriptor) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *InterfaceDescriptor) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *InterfaceDescriptor) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *InterfaceDescriptor) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *InterfaceDescriptor) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *InterfaceDescriptor) GetContentDigest() string {
	if m != nil {
		return m.ContentDigest
	}
	return ""
}

func init() {
	proto.RegisterType((*ServiceContract)(nil), "v1.ServiceContract")
	proto.RegisterMapType((map[string]string)(nil), "v1.ServiceContract.MetadataEntry")
	proto.RegisterType((*InterfaceDescriptor)(nil), "v1.InterfaceDescriptor")
	proto.RegisterEnum("v1.InterfaceDescriptor_Source", InterfaceDescriptor_Source_name, InterfaceDescriptor_Source_value)
}

func init() { proto.RegisterFile("contract.proto", fileDescriptor_contract_6b948cfbd95c06a7) }

var fileDescriptor_contract_6b948cfbd95c06a7 = []byte{
	// 557 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x5f, 0x6b, 0x1a, 0x4f,
	0x14, 0xfd, 0xb9, 0x9a, 0x55, 0xaf, 0x89, 0xca, 0xfc, 0x42, 0x3a, 0x84, 0x52, 0x52, 0xa1, 0x90,
	0x97, 0xee, 0x62, 0x0a, 0x4d, 0x69, 0xe9, 0x4b, 0x62, 0x1f, 0x4a, 0x89, 0x2d, 0x86, 0x52, 0xe8,
	0x4b, 0x98, 0x8c, 0x37, 0x3a, 0xd4, 0x9d, 0x59, 0x76, 0xc6, 0x05, 0x3f, 0x44, 0x1f, 0xfb, 0xd9,
	0xfa, 0x75, 0xca, 0xfc, 0xd1, 0xaa, 0xd1, 0x3e, 0x79, 0xcf, 0xb9, 0x73, 0x8f, 0x7b, 0xef, 0x39,
	0xd0, 0xe6, 0x4a, 0x9a, 0x82, 0x71, 0x93, 0xe4, 0x85, 0x32, 0x8a, 0x44, 0x65, 0xbf, 0xf7, 0xb3,
	0x06, 0x9d, 0x5b, 0x2c, 0x4a, 0xc1, 0xf1, 0x3a, 0x74, 0x49, 0x1b, 0x22, 0x31, 0xa6, 0x95, 0xb3,
	0xca, 0x79, 0x73, 0x14, 0x89, 0x31, 0x21, 0x50, 0x93, 0x2c, 0x43, 0x1a, 0x39, 0xc6, 0xd5, 0xe4,
	0x29, 0x34, 0xed, 0xaf, 0xce, 0x19, 0x47, 0x5a, 0x75, 0x8d, 0xbf, 0x04, 0xa1, 0x50, 0xd7, 0x5e,
	0x94, 0xd6, 0x5c, 0x6f, 0x09, 0xc9, 0x29, 0x34, 0xdc, 0x9f, 0x73, 0x35, 0xa3, 0x07, 0xae, 0xb5,
	0xc2, 0x76, 0xaa, 0xc4, 0x42, 0x0b, 0x25, 0x69, 0xec, 0xa7, 0x02, 0xb4, 0x53, 0x05, 0x96, 0xc2,
	0xb5, 0xea, 0x7e, 0x6a, 0x89, 0xed, 0x94, 0xdd, 0x0b, 0xa5, 0xa1, 0x0d, 0x3f, 0x15, 0x20, 0xb9,
	0x04, 0x10, 0xd2, 0x60, 0xf1, 0xc0, 0x38, 0x6a, 0xda, 0x3c, 0xab, 0x9e, 0xb7, 0x2e, 0x9e, 0x24,
	0x65, 0x3f, 0xf9, 0xb8, 0x64, 0x07, 0xa8, 0x79, 0x21, 0x72, 0xa3, 0x8a, 0xd1, 0xda, 0x53, 0x72,
	0x0c, 0x07, 0xdc, 0x88, 0x0c, 0x29, 0x38, 0x41, 0x0f, 0x2c, 0x9b, 0x39, 0xb6, 0xe5, 0x59, 0x07,
	0xc8, 0x09, 0xc4, 0xda, 0x30, 0x33, 0xd7, 0xf4, 0xd0, 0xd1, 0x01, 0xd9, 0xa3, 0x99, 0x45, 0x8e,
	0xb4, 0xed, 0x8f, 0x66, 0x6b, 0xf2, 0x1e, 0x1a, 0x19, 0x1a, 0x36, 0x66, 0x86, 0xd1, 0x8e, 0xfb,
	0x9c, 0xe7, 0xf6, 0x73, 0xb6, 0xee, 0x9f, 0xdc, 0x84, 0x37, 0x1f, 0xa4, 0x29, 0x16, 0xa3, 0xd5,
	0x08, 0x79, 0xe1, 0x1d, 0x44, 0x69, 0xee, 0xc6, 0x62, 0x82, 0xda, 0xd0, 0xae, 0x13, 0x3f, 0x0a,
	0xec, 0xc0, 0x91, 0xa7, 0xef, 0xe0, 0x68, 0x43, 0x81, 0x74, 0xa1, 0xfa, 0x03, 0x17, 0xc1, 0x50,
	0x5b, 0xda, 0x55, 0x4a, 0x36, 0x9b, 0x2f, 0x2d, 0xf5, 0xe0, 0x6d, 0xf4, 0xa6, 0xd2, 0xfb, 0x5d,
	0x85, 0xff, 0x77, 0x9c, 0xe7, 0x51, 0x26, 0x4e, 0x20, 0xce, 0xd0, 0x4c, 0xd5, 0x38, 0x48, 0x04,
	0x64, 0xd7, 0xce, 0x99, 0x99, 0x86, 0x48, 0xb8, 0x7a, 0xdd, 0xa1, 0xda, 0xa6, 0x43, 0xaf, 0x21,
	0xd6, 0x6a, 0x5e, 0x70, 0x74, 0x59, 0x68, 0x5f, 0x3c, 0xdb, 0xe3, 0x4e, 0x72, 0xeb, 0x5e, 0x8d,
	0xc2, 0xeb, 0x8d, 0x3c, 0xc4, 0x5b, 0x79, 0x58, 0x99, 0x57, 0xdf, 0x69, 0x5e, 0x63, 0xdd, 0xbc,
	0x65, 0xb2, 0x9b, 0xfb, 0x92, 0x0d, 0xff, 0x48, 0x76, 0x6b, 0x7f, 0xb2, 0x0f, 0xf7, 0x27, 0xfb,
	0x68, 0x33, 0xd9, 0xbb, 0x62, 0xf2, 0xd8, 0xe7, 0xce, 0x0e, 0x9f, 0x7b, 0x2f, 0x21, 0xf6, 0x67,
	0x21, 0x2d, 0xa8, 0x7f, 0x1d, 0x7e, 0x1a, 0x7e, 0xfe, 0x36, 0xec, 0xfe, 0x47, 0x00, 0xe2, 0x1b,
	0x26, 0xe7, 0x6c, 0xd6, 0xad, 0xd8, 0xfa, 0x7a, 0x26, 0x50, 0x9a, 0x6e, 0x74, 0xf5, 0xab, 0x02,
	0x97, 0x5c, 0x65, 0x89, 0x41, 0xc9, 0x51, 0x9a, 0x24, 0x57, 0x33, 0x56, 0x08, 0x9d, 0xe8, 0x1c,
	0xb9, 0x78, 0x10, 0x9c, 0x19, 0xa1, 0x64, 0xc2, 0x72, 0x61, 0x3d, 0x08, 0x4b, 0x25, 0x19, 0x93,
	0x6c, 0x82, 0x57, 0xc7, 0x5b, 0x11, 0xfd, 0x62, 0x17, 0xfb, 0x3e, 0x98, 0x08, 0x33, 0x9d, 0xdf,
	0x27, 0x5c, 0x65, 0x69, 0x50, 0xcb, 0x50, 0x4f, 0xd3, 0x0d, 0xc5, 0xd4, 0x5b, 0x96, 0x4e, 0x54,
	0xca, 0x72, 0x91, 0x96, 0xfd, 0x34, 0x68, 0xdf, 0x79, 0xed, 0xfb, 0xd8, 0x5d, 0xe9, 0xd5, 0x9f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x2c, 0x04, 0x10, 0x53, 0x9e, 0x04, 0x00, 0x00,
}
