// Code generated by protoc-gen-go. DO NOT EDIT.
// source: heartbeat.proto

package service_manage // import "github.com/polarismesh/specification/source/go/api/v1/service_manage"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HeartbeatRecord struct {
	InstanceId           string   `protobuf:"bytes,1,opt,name=instanceId,json=instance_id,proto3" json:"instanceId,omitempty"`
	LastHeartbeatSec     int64    `protobuf:"varint,6,opt,name=lastHeartbeatSec,json=last_heartbeat_sec,proto3" json:"lastHeartbeatSec,omitempty"`
	Exist                bool     `protobuf:"varint,7,opt,name=exist,proto3" json:"exist,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatRecord) Reset()         { *m = HeartbeatRecord{} }
func (m *HeartbeatRecord) String() string { return proto.CompactTextString(m) }
func (*HeartbeatRecord) ProtoMessage()    {}
func (*HeartbeatRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_heartbeat_444c95e923f2483e, []int{0}
}
func (m *HeartbeatRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatRecord.Unmarshal(m, b)
}
func (m *HeartbeatRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatRecord.Marshal(b, m, deterministic)
}
func (dst *HeartbeatRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatRecord.Merge(dst, src)
}
func (m *HeartbeatRecord) XXX_Size() int {
	return xxx_messageInfo_HeartbeatRecord.Size(m)
}
func (m *HeartbeatRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatRecord.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatRecord proto.InternalMessageInfo

func (m *HeartbeatRecord) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

func (m *HeartbeatRecord) GetLastHeartbeatSec() int64 {
	if m != nil {
		return m.LastHeartbeatSec
	}
	return 0
}

func (m *HeartbeatRecord) GetExist() bool {
	if m != nil {
		return m.Exist
	}
	return false
}

type InstanceHeartbeat struct {
	InstanceId           string   `protobuf:"bytes,1,opt,name=instanceId,json=instance_id,proto3" json:"instanceId,omitempty"`
	Service              string   `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Namespace            string   `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Host                 string   `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	Port                 uint32   `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstanceHeartbeat) Reset()         { *m = InstanceHeartbeat{} }
func (m *InstanceHeartbeat) String() string { return proto.CompactTextString(m) }
func (*InstanceHeartbeat) ProtoMessage()    {}
func (*InstanceHeartbeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_heartbeat_444c95e923f2483e, []int{1}
}
func (m *InstanceHeartbeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceHeartbeat.Unmarshal(m, b)
}
func (m *InstanceHeartbeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceHeartbeat.Marshal(b, m, deterministic)
}
func (dst *InstanceHeartbeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceHeartbeat.Merge(dst, src)
}
func (m *InstanceHeartbeat) XXX_Size() int {
	return xxx_messageInfo_InstanceHeartbeat.Size(m)
}
func (m *InstanceHeartbeat) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceHeartbeat.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceHeartbeat proto.InternalMessageInfo

func (m *InstanceHeartbeat) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

func (m *InstanceHeartbeat) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *InstanceHeartbeat) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *InstanceHeartbeat) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *InstanceHeartbeat) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type HeartbeatsRequest struct {
	Heartbeats           []*InstanceHeartbeat `protobuf:"bytes,1,rep,name=heartbeats,proto3" json:"heartbeats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *HeartbeatsRequest) Reset()         { *m = HeartbeatsRequest{} }
func (m *HeartbeatsRequest) String() string { return proto.CompactTextString(m) }
func (*HeartbeatsRequest) ProtoMessage()    {}
func (*HeartbeatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_heartbeat_444c95e923f2483e, []int{2}
}
func (m *HeartbeatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatsRequest.Unmarshal(m, b)
}
func (m *HeartbeatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatsRequest.Marshal(b, m, deterministic)
}
func (dst *HeartbeatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatsRequest.Merge(dst, src)
}
func (m *HeartbeatsRequest) XXX_Size() int {
	return xxx_messageInfo_HeartbeatsRequest.Size(m)
}
func (m *HeartbeatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatsRequest proto.InternalMessageInfo

func (m *HeartbeatsRequest) GetHeartbeats() []*InstanceHeartbeat {
	if m != nil {
		return m.Heartbeats
	}
	return nil
}

type HeartbeatsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatsResponse) Reset()         { *m = HeartbeatsResponse{} }
func (m *HeartbeatsResponse) String() string { return proto.CompactTextString(m) }
func (*HeartbeatsResponse) ProtoMessage()    {}
func (*HeartbeatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_heartbeat_444c95e923f2483e, []int{3}
}
func (m *HeartbeatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatsResponse.Unmarshal(m, b)
}
func (m *HeartbeatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatsResponse.Marshal(b, m, deterministic)
}
func (dst *HeartbeatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatsResponse.Merge(dst, src)
}
func (m *HeartbeatsResponse) XXX_Size() int {
	return xxx_messageInfo_HeartbeatsResponse.Size(m)
}
func (m *HeartbeatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatsResponse proto.InternalMessageInfo

type GetHeartbeatsRequest struct {
	InstanceIds          []string `protobuf:"bytes,1,rep,name=instanceIds,json=instance_ids,proto3" json:"instanceIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHeartbeatsRequest) Reset()         { *m = GetHeartbeatsRequest{} }
func (m *GetHeartbeatsRequest) String() string { return proto.CompactTextString(m) }
func (*GetHeartbeatsRequest) ProtoMessage()    {}
func (*GetHeartbeatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_heartbeat_444c95e923f2483e, []int{4}
}
func (m *GetHeartbeatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHeartbeatsRequest.Unmarshal(m, b)
}
func (m *GetHeartbeatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHeartbeatsRequest.Marshal(b, m, deterministic)
}
func (dst *GetHeartbeatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHeartbeatsRequest.Merge(dst, src)
}
func (m *GetHeartbeatsRequest) XXX_Size() int {
	return xxx_messageInfo_GetHeartbeatsRequest.Size(m)
}
func (m *GetHeartbeatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHeartbeatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHeartbeatsRequest proto.InternalMessageInfo

func (m *GetHeartbeatsRequest) GetInstanceIds() []string {
	if m != nil {
		return m.InstanceIds
	}
	return nil
}

type GetHeartbeatsResponse struct {
	Records              []*HeartbeatRecord `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetHeartbeatsResponse) Reset()         { *m = GetHeartbeatsResponse{} }
func (m *GetHeartbeatsResponse) String() string { return proto.CompactTextString(m) }
func (*GetHeartbeatsResponse) ProtoMessage()    {}
func (*GetHeartbeatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_heartbeat_444c95e923f2483e, []int{5}
}
func (m *GetHeartbeatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHeartbeatsResponse.Unmarshal(m, b)
}
func (m *GetHeartbeatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHeartbeatsResponse.Marshal(b, m, deterministic)
}
func (dst *GetHeartbeatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHeartbeatsResponse.Merge(dst, src)
}
func (m *GetHeartbeatsResponse) XXX_Size() int {
	return xxx_messageInfo_GetHeartbeatsResponse.Size(m)
}
func (m *GetHeartbeatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHeartbeatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetHeartbeatsResponse proto.InternalMessageInfo

func (m *GetHeartbeatsResponse) GetRecords() []*HeartbeatRecord {
	if m != nil {
		return m.Records
	}
	return nil
}

type DelHeartbeatsRequest struct {
	InstanceIds          []string `protobuf:"bytes,1,rep,name=instanceIds,json=instance_ids,proto3" json:"instanceIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelHeartbeatsRequest) Reset()         { *m = DelHeartbeatsRequest{} }
func (m *DelHeartbeatsRequest) String() string { return proto.CompactTextString(m) }
func (*DelHeartbeatsRequest) ProtoMessage()    {}
func (*DelHeartbeatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_heartbeat_444c95e923f2483e, []int{6}
}
func (m *DelHeartbeatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelHeartbeatsRequest.Unmarshal(m, b)
}
func (m *DelHeartbeatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelHeartbeatsRequest.Marshal(b, m, deterministic)
}
func (dst *DelHeartbeatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelHeartbeatsRequest.Merge(dst, src)
}
func (m *DelHeartbeatsRequest) XXX_Size() int {
	return xxx_messageInfo_DelHeartbeatsRequest.Size(m)
}
func (m *DelHeartbeatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DelHeartbeatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DelHeartbeatsRequest proto.InternalMessageInfo

func (m *DelHeartbeatsRequest) GetInstanceIds() []string {
	if m != nil {
		return m.InstanceIds
	}
	return nil
}

type DelHeartbeatsResponse struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 string   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelHeartbeatsResponse) Reset()         { *m = DelHeartbeatsResponse{} }
func (m *DelHeartbeatsResponse) String() string { return proto.CompactTextString(m) }
func (*DelHeartbeatsResponse) ProtoMessage()    {}
func (*DelHeartbeatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_heartbeat_444c95e923f2483e, []int{7}
}
func (m *DelHeartbeatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelHeartbeatsResponse.Unmarshal(m, b)
}
func (m *DelHeartbeatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelHeartbeatsResponse.Marshal(b, m, deterministic)
}
func (dst *DelHeartbeatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelHeartbeatsResponse.Merge(dst, src)
}
func (m *DelHeartbeatsResponse) XXX_Size() int {
	return xxx_messageInfo_DelHeartbeatsResponse.Size(m)
}
func (m *DelHeartbeatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DelHeartbeatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DelHeartbeatsResponse proto.InternalMessageInfo

func (m *DelHeartbeatsResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DelHeartbeatsResponse) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func init() {
	proto.RegisterType((*HeartbeatRecord)(nil), "v1.HeartbeatRecord")
	proto.RegisterType((*InstanceHeartbeat)(nil), "v1.InstanceHeartbeat")
	proto.RegisterType((*HeartbeatsRequest)(nil), "v1.HeartbeatsRequest")
	proto.RegisterType((*HeartbeatsResponse)(nil), "v1.HeartbeatsResponse")
	proto.RegisterType((*GetHeartbeatsRequest)(nil), "v1.GetHeartbeatsRequest")
	proto.RegisterType((*GetHeartbeatsResponse)(nil), "v1.GetHeartbeatsResponse")
	proto.RegisterType((*DelHeartbeatsRequest)(nil), "v1.DelHeartbeatsRequest")
	proto.RegisterType((*DelHeartbeatsResponse)(nil), "v1.DelHeartbeatsResponse")
}

func init() { proto.RegisterFile("heartbeat.proto", fileDescriptor_heartbeat_444c95e923f2483e) }

var fileDescriptor_heartbeat_444c95e923f2483e = []byte{
	// 423 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x4d, 0x8b, 0x13, 0x41,
	0x10, 0x65, 0x92, 0x6c, 0xb2, 0xa9, 0x18, 0x76, 0xb7, 0x4d, 0xa0, 0x11, 0xc1, 0x71, 0x4e, 0x73,
	0xd0, 0x19, 0xa2, 0x88, 0x78, 0x12, 0x64, 0x51, 0x77, 0x8f, 0xed, 0xcd, 0x4b, 0xe8, 0x74, 0x6a,
	0x93, 0x86, 0x4c, 0xf7, 0xd8, 0xd5, 0x09, 0x1e, 0x04, 0xff, 0x84, 0x3f, 0x58, 0xa6, 0xe7, 0x63,
	0x63, 0xf6, 0x20, 0xec, 0xad, 0xfa, 0x55, 0xbd, 0x57, 0xef, 0x51, 0x0d, 0x17, 0x5b, 0x94, 0xce,
	0xaf, 0x50, 0xfa, 0xac, 0x74, 0xd6, 0x5b, 0xd6, 0x3b, 0x2c, 0x9e, 0x4d, 0x09, 0xdd, 0x41, 0x2b,
	0xac, 0xa1, 0xe4, 0x17, 0x5c, 0x7c, 0x6d, 0xa7, 0x04, 0x2a, 0xeb, 0xd6, 0xec, 0x05, 0x80, 0x36,
	0xe4, 0xa5, 0x51, 0x78, 0xb3, 0xe6, 0x51, 0x1c, 0xa5, 0x63, 0x31, 0x69, 0x91, 0xa5, 0x5e, 0xb3,
	0x57, 0x70, 0xb9, 0x93, 0xe4, 0x3b, 0xde, 0x37, 0x54, 0x7c, 0x18, 0x47, 0x69, 0x5f, 0xb0, 0x0a,
	0x5f, 0x76, 0x6b, 0x97, 0x84, 0x8a, 0xcd, 0xe0, 0x0c, 0x7f, 0x6a, 0xf2, 0x7c, 0x14, 0x47, 0xe9,
	0xb9, 0xa8, 0x1f, 0xb7, 0x83, 0xf3, 0xde, 0xe5, 0x30, 0xf9, 0x13, 0xc1, 0xd5, 0x4d, 0xa3, 0xdc,
	0xc9, 0xfd, 0xdf, 0x00, 0x87, 0x51, 0x93, 0x82, 0xf7, 0x42, 0xb7, 0x7d, 0xb2, 0xe7, 0x30, 0x36,
	0xb2, 0x40, 0x2a, 0xa5, 0x42, 0xde, 0x0f, 0xbd, 0x7b, 0x80, 0x31, 0x18, 0x6c, 0x2d, 0x79, 0x3e,
	0x08, 0x8d, 0x50, 0x57, 0x58, 0x69, 0x9d, 0xe7, 0x67, 0x71, 0x94, 0x4e, 0x45, 0xa8, 0x93, 0x5b,
	0xb8, 0xea, 0xdc, 0x90, 0xc0, 0x1f, 0x7b, 0x24, 0xcf, 0xde, 0x01, 0x74, 0xc1, 0x88, 0x47, 0x71,
	0x3f, 0x9d, 0xbc, 0x99, 0x67, 0x87, 0x45, 0xf6, 0x20, 0x80, 0x38, 0x1a, 0x4c, 0x66, 0xc0, 0x8e,
	0xb5, 0xa8, 0xb4, 0x86, 0x30, 0xf9, 0x00, 0xb3, 0x2f, 0xe8, 0x1f, 0x2e, 0x79, 0x09, 0x93, 0xfb,
	0xe8, 0xf5, 0x96, 0xb1, 0x78, 0x72, 0x94, 0x9d, 0x92, 0xcf, 0x30, 0x3f, 0xa1, 0xd6, 0x9a, 0xec,
	0x35, 0x8c, 0x5c, 0xb8, 0x60, 0xeb, 0xee, 0x69, 0xe5, 0xee, 0xe4, 0xba, 0xa2, 0x9d, 0xa9, 0x2c,
	0x5c, 0xe3, 0xee, 0x51, 0x16, 0x3e, 0xc2, 0xfc, 0x84, 0xda, 0x58, 0x60, 0x30, 0x50, 0x76, 0x8d,
	0xe1, 0x66, 0x53, 0x11, 0xea, 0x0a, 0xd3, 0xe6, 0xce, 0x36, 0x97, 0x0a, 0xf5, 0xa7, 0xdf, 0xf0,
	0x5e, 0xd9, 0x22, 0xf3, 0x68, 0x14, 0x1a, 0x9f, 0x95, 0x76, 0x27, 0x9d, 0xa6, 0x8c, 0x4a, 0x54,
	0xfa, 0x4e, 0x2b, 0xe9, 0xb5, 0x35, 0x99, 0x2c, 0x75, 0x15, 0xa0, 0xfd, 0xaf, 0x85, 0x34, 0x72,
	0x83, 0xdf, 0xaf, 0x37, 0xda, 0x6f, 0xf7, 0xab, 0x4c, 0xd9, 0x22, 0x6f, 0x78, 0x05, 0xd2, 0x36,
	0xff, 0x87, 0x9b, 0x93, 0xdd, 0x3b, 0x85, 0xf9, 0xc6, 0xe6, 0xb2, 0xd4, 0xf9, 0x61, 0x91, 0x37,
	0x2a, 0xcb, 0x5a, 0x65, 0x35, 0x0c, 0xbf, 0xff, 0xed, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x83,
	0x12, 0x25, 0xbc, 0x23, 0x03, 0x00, 0x00,
}
