// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model.proto

package model // import "github.com/polarismesh/specification/source/go/api/v1/model"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MatchString_MatchStringType int32

const (
	// Equivalent match
	MatchString_EXACT MatchString_MatchStringType = 0
	// Regular match
	MatchString_REGEX MatchString_MatchStringType = 1
	// Not equals match
	MatchString_NOT_EQUALS MatchString_MatchStringType = 2
	// Include match
	MatchString_IN MatchString_MatchStringType = 3
	// Not include match
	MatchString_NOT_IN MatchString_MatchStringType = 4
)

var MatchString_MatchStringType_name = map[int32]string{
	0: "EXACT",
	1: "REGEX",
	2: "NOT_EQUALS",
	3: "IN",
	4: "NOT_IN",
}
var MatchString_MatchStringType_value = map[string]int32{
	"EXACT":      0,
	"REGEX":      1,
	"NOT_EQUALS": 2,
	"IN":         3,
	"NOT_IN":     4,
}

func (x MatchString_MatchStringType) String() string {
	return proto.EnumName(MatchString_MatchStringType_name, int32(x))
}
func (MatchString_MatchStringType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_model_32a907ae6c81d257, []int{1, 0}
}

type MatchString_ValueType int32

const (
	MatchString_TEXT      MatchString_ValueType = 0
	MatchString_PARAMETER MatchString_ValueType = 1
	MatchString_VARIABLE  MatchString_ValueType = 2
)

var MatchString_ValueType_name = map[int32]string{
	0: "TEXT",
	1: "PARAMETER",
	2: "VARIABLE",
}
var MatchString_ValueType_value = map[string]int32{
	"TEXT":      0,
	"PARAMETER": 1,
	"VARIABLE":  2,
}

func (x MatchString_ValueType) String() string {
	return proto.EnumName(MatchString_ValueType_name, int32(x))
}
func (MatchString_ValueType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_model_32a907ae6c81d257, []int{1, 1}
}

type Location struct {
	Region               *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	Zone                 *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=zone,proto3" json:"zone,omitempty"`
	Campus               *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=campus,proto3" json:"campus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_model_32a907ae6c81d257, []int{0}
}
func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (dst *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(dst, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetRegion() *wrapperspb.StringValue {
	if m != nil {
		return m.Region
	}
	return nil
}

func (m *Location) GetZone() *wrapperspb.StringValue {
	if m != nil {
		return m.Zone
	}
	return nil
}

func (m *Location) GetCampus() *wrapperspb.StringValue {
	if m != nil {
		return m.Campus
	}
	return nil
}

type MatchString struct {
	Type                 MatchString_MatchStringType `protobuf:"varint,1,opt,name=type,proto3,enum=v1.MatchString_MatchStringType" json:"type,omitempty"`
	Value                *wrapperspb.StringValue     `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	ValueType            MatchString_ValueType       `protobuf:"varint,3,opt,name=value_type,json=valueType,proto3,enum=v1.MatchString_ValueType" json:"value_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *MatchString) Reset()         { *m = MatchString{} }
func (m *MatchString) String() string { return proto.CompactTextString(m) }
func (*MatchString) ProtoMessage()    {}
func (*MatchString) Descriptor() ([]byte, []int) {
	return fileDescriptor_model_32a907ae6c81d257, []int{1}
}
func (m *MatchString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchString.Unmarshal(m, b)
}
func (m *MatchString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchString.Marshal(b, m, deterministic)
}
func (dst *MatchString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchString.Merge(dst, src)
}
func (m *MatchString) XXX_Size() int {
	return xxx_messageInfo_MatchString.Size(m)
}
func (m *MatchString) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchString.DiscardUnknown(m)
}

var xxx_messageInfo_MatchString proto.InternalMessageInfo

func (m *MatchString) GetType() MatchString_MatchStringType {
	if m != nil {
		return m.Type
	}
	return MatchString_EXACT
}

func (m *MatchString) GetValue() *wrapperspb.StringValue {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *MatchString) GetValueType() MatchString_ValueType {
	if m != nil {
		return m.ValueType
	}
	return MatchString_TEXT
}

type StringList struct {
	Values               []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringList) Reset()         { *m = StringList{} }
func (m *StringList) String() string { return proto.CompactTextString(m) }
func (*StringList) ProtoMessage()    {}
func (*StringList) Descriptor() ([]byte, []int) {
	return fileDescriptor_model_32a907ae6c81d257, []int{2}
}
func (m *StringList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringList.Unmarshal(m, b)
}
func (m *StringList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringList.Marshal(b, m, deterministic)
}
func (dst *StringList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringList.Merge(dst, src)
}
func (m *StringList) XXX_Size() int {
	return xxx_messageInfo_StringList.Size(m)
}
func (m *StringList) XXX_DiscardUnknown() {
	xxx_messageInfo_StringList.DiscardUnknown(m)
}

var xxx_messageInfo_StringList proto.InternalMessageInfo

func (m *StringList) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*Location)(nil), "v1.Location")
	proto.RegisterType((*MatchString)(nil), "v1.MatchString")
	proto.RegisterType((*StringList)(nil), "v1.StringList")
	proto.RegisterEnum("v1.MatchString_MatchStringType", MatchString_MatchStringType_name, MatchString_MatchStringType_value)
	proto.RegisterEnum("v1.MatchString_ValueType", MatchString_ValueType_name, MatchString_ValueType_value)
}

func init() { proto.RegisterFile("model.proto", fileDescriptor_model_32a907ae6c81d257) }

var fileDescriptor_model_32a907ae6c81d257 = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0xaf, 0x93, 0x40,
	0x14, 0xc5, 0xe5, 0xcf, 0x23, 0xe5, 0x56, 0x9f, 0x64, 0x16, 0x06, 0x8d, 0xd1, 0x17, 0xe2, 0xe2,
	0xad, 0x18, 0xcb, 0x73, 0x61, 0x62, 0x5c, 0xf0, 0xcc, 0xc4, 0x34, 0xd2, 0xaa, 0x14, 0x9b, 0xc6,
	0x4d, 0x43, 0x71, 0x4a, 0x27, 0x01, 0x66, 0xc2, 0x00, 0xa6, 0x7e, 0x22, 0xb7, 0x7e, 0x43, 0xc3,
	0xd0, 0xbe, 0x34, 0x5d, 0x75, 0x77, 0x98, 0x7b, 0xce, 0xfd, 0x9d, 0x90, 0x0b, 0xe3, 0x92, 0xff,
	0xa2, 0x85, 0x2f, 0x6a, 0xde, 0x70, 0xa4, 0x77, 0x93, 0x17, 0xaf, 0x72, 0xce, 0xf3, 0x82, 0x62,
	0xf5, 0xb2, 0x69, 0xb7, 0xf8, 0x77, 0x9d, 0x0a, 0x41, 0x6b, 0x39, 0x78, 0xbc, 0xbf, 0x1a, 0x8c,
	0x22, 0x9e, 0xa5, 0x0d, 0xe3, 0x15, 0x7a, 0x07, 0x56, 0x4d, 0x73, 0xc6, 0x2b, 0x57, 0xbb, 0xd1,
	0x6e, 0xc7, 0xc1, 0x4b, 0x7f, 0x48, 0xfb, 0xc7, 0xb4, 0xbf, 0x68, 0x6a, 0x56, 0xe5, 0xcb, 0xb4,
	0x68, 0x69, 0x7c, 0xf0, 0xa2, 0xb7, 0x60, 0xfe, 0xe1, 0x15, 0x75, 0xf5, 0x0b, 0x32, 0xca, 0xd9,
	0x73, 0xb2, 0xb4, 0x14, 0xad, 0x74, 0x8d, 0x4b, 0x38, 0x83, 0xd7, 0xfb, 0xa7, 0xc3, 0x78, 0x96,
	0x36, 0xd9, 0x6e, 0x18, 0xa2, 0x3b, 0x30, 0x9b, 0xbd, 0xa0, 0xaa, 0xeb, 0x75, 0xf0, 0xda, 0xef,
	0x26, 0xfe, 0xc9, 0xf8, 0x54, 0x27, 0x7b, 0x41, 0x63, 0x65, 0x46, 0x01, 0x5c, 0x75, 0xfd, 0xd6,
	0x8b, 0xda, 0x0e, 0x56, 0xf4, 0x1e, 0x40, 0x89, 0xb5, 0xc2, 0x19, 0x0a, 0xf7, 0xfc, 0x1c, 0xa7,
	0x12, 0x0a, 0x64, 0x77, 0x47, 0xe9, 0x7d, 0x81, 0xa7, 0x67, 0x35, 0x90, 0x0d, 0x57, 0x64, 0x15,
	0x7e, 0x4a, 0x9c, 0x47, 0xbd, 0x8c, 0xc9, 0x67, 0xb2, 0x72, 0x34, 0x74, 0x0d, 0x30, 0xff, 0x9a,
	0xac, 0xc9, 0xf7, 0x1f, 0x61, 0xb4, 0x70, 0x74, 0x64, 0x81, 0x3e, 0x9d, 0x3b, 0x06, 0x02, 0xb0,
	0xfa, 0xf7, 0xe9, 0xdc, 0x31, 0xbd, 0x00, 0xec, 0x07, 0x08, 0x1a, 0x81, 0x99, 0x90, 0x55, 0xbf,
	0xe5, 0x09, 0xd8, 0xdf, 0xc2, 0x38, 0x9c, 0x91, 0x84, 0xc4, 0x8e, 0x86, 0x1e, 0xc3, 0x68, 0x19,
	0xc6, 0xd3, 0xf0, 0x3e, 0x22, 0x8e, 0xee, 0xbd, 0x01, 0x18, 0xd8, 0x11, 0x93, 0x0d, 0x7a, 0x06,
	0x96, 0xea, 0x26, 0x5d, 0xed, 0xc6, 0xb8, 0xb5, 0xe3, 0xc3, 0xd7, 0xfd, 0xc7, 0x9f, 0x1f, 0x72,
	0xd6, 0xec, 0xda, 0x8d, 0x9f, 0xf1, 0x12, 0x0b, 0x5e, 0xa4, 0x35, 0x93, 0x25, 0x95, 0x3b, 0x2c,
	0x05, 0xcd, 0xd8, 0x96, 0x0d, 0xf7, 0x81, 0x25, 0x6f, 0xeb, 0x8c, 0xe2, 0x9c, 0xe3, 0x54, 0x30,
	0xdc, 0x4d, 0xb0, 0xba, 0xb6, 0x8d, 0xa5, 0x7e, 0xde, 0xdd, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x2f, 0x6d, 0x82, 0x41, 0x7d, 0x02, 0x00, 0x00,
}
