// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ratelimit.proto

package traffic_manage // import "github.com/polarismesh/specification/source/go/api/v1/traffic_manage"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import model "github.com/polarismesh/specification/source/go/api/v1/model"
import durationpb "google.golang.org/protobuf/types/known/durationpb"
import wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 限流资源
type Rule_Resource int32

const (
	// 针对QPS进行限流
	Rule_QPS Rule_Resource = 0
	// 针对并发数进行限流
	Rule_CONCURRENCY Rule_Resource = 1
	// 针对CPU使用率进行限流
	Rule_CPU_BBR Rule_Resource = 2
)

var Rule_Resource_name = map[int32]string{
	0: "QPS",
	1: "CONCURRENCY",
	2: "CPU_BBR",
}
var Rule_Resource_value = map[string]int32{
	"QPS":         0,
	"CONCURRENCY": 1,
	"CPU_BBR":     2,
}

func (x Rule_Resource) String() string {
	return proto.EnumName(Rule_Resource_name, int32(x))
}
func (Rule_Resource) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ratelimit_fefd9d07bd36fe0f, []int{1, 0}
}

// 限流类型
// global全局限流(默认)或者local单机限流
type Rule_Type int32

const (
	Rule_GLOBAL Rule_Type = 0
	Rule_LOCAL  Rule_Type = 1
)

var Rule_Type_name = map[int32]string{
	0: "GLOBAL",
	1: "LOCAL",
}
var Rule_Type_value = map[string]int32{
	"GLOBAL": 0,
	"LOCAL":  1,
}

func (x Rule_Type) String() string {
	return proto.EnumName(Rule_Type_name, int32(x))
}
func (Rule_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ratelimit_fefd9d07bd36fe0f, []int{1, 1}
}

// 限流阈值模
type Rule_AmountMode int32

const (
	Rule_GLOBAL_TOTAL  Rule_AmountMode = 0
	Rule_SHARE_EQUALLY Rule_AmountMode = 1
)

var Rule_AmountMode_name = map[int32]string{
	0: "GLOBAL_TOTAL",
	1: "SHARE_EQUALLY",
}
var Rule_AmountMode_value = map[string]int32{
	"GLOBAL_TOTAL":  0,
	"SHARE_EQUALLY": 1,
}

func (x Rule_AmountMode) String() string {
	return proto.EnumName(Rule_AmountMode_name, int32(x))
}
func (Rule_AmountMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ratelimit_fefd9d07bd36fe0f, []int{1, 2}
}

// 与限流集群连接失败时降级模式
type Rule_FailoverType int32

const (
	Rule_FAILOVER_LOCAL Rule_FailoverType = 0
	Rule_FAILOVER_PASS  Rule_FailoverType = 1
)

var Rule_FailoverType_name = map[int32]string{
	0: "FAILOVER_LOCAL",
	1: "FAILOVER_PASS",
}
var Rule_FailoverType_value = map[string]int32{
	"FAILOVER_LOCAL": 0,
	"FAILOVER_PASS":  1,
}

func (x Rule_FailoverType) String() string {
	return proto.EnumName(Rule_FailoverType_name, int32(x))
}
func (Rule_FailoverType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ratelimit_fefd9d07bd36fe0f, []int{1, 3}
}

// label type for gateway request
type MatchArgument_Type int32

const (
	// custom arguments
	MatchArgument_CUSTOM MatchArgument_Type = 0
	// method, match the http post/get/put/delete or grpc method
	MatchArgument_METHOD MatchArgument_Type = 1
	// header, match the http header, dubbo attachment, grpc header
	MatchArgument_HEADER MatchArgument_Type = 2
	// query, match the http query, dubbo argument
	MatchArgument_QUERY MatchArgument_Type = 3
	// caller service
	MatchArgument_CALLER_SERVICE MatchArgument_Type = 4
	// caller host ip
	MatchArgument_CALLER_IP MatchArgument_Type = 5
)

var MatchArgument_Type_name = map[int32]string{
	0: "CUSTOM",
	1: "METHOD",
	2: "HEADER",
	3: "QUERY",
	4: "CALLER_SERVICE",
	5: "CALLER_IP",
}
var MatchArgument_Type_value = map[string]int32{
	"CUSTOM":         0,
	"METHOD":         1,
	"HEADER":         2,
	"QUERY":          3,
	"CALLER_SERVICE": 4,
	"CALLER_IP":      5,
}

func (x MatchArgument_Type) String() string {
	return proto.EnumName(MatchArgument_Type_name, int32(x))
}
func (MatchArgument_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ratelimit_fefd9d07bd36fe0f, []int{2, 0}
}

// 同一服务下限流规则集合
type RateLimit struct {
	// 限流规则集合
	Rules []*Rule `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	// 限流规则汇总的revision信息
	Revision             *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *RateLimit) Reset()         { *m = RateLimit{} }
func (m *RateLimit) String() string { return proto.CompactTextString(m) }
func (*RateLimit) ProtoMessage()    {}
func (*RateLimit) Descriptor() ([]byte, []int) {
	return fileDescriptor_ratelimit_fefd9d07bd36fe0f, []int{0}
}
func (m *RateLimit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RateLimit.Unmarshal(m, b)
}
func (m *RateLimit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RateLimit.Marshal(b, m, deterministic)
}
func (dst *RateLimit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RateLimit.Merge(dst, src)
}
func (m *RateLimit) XXX_Size() int {
	return xxx_messageInfo_RateLimit.Size(m)
}
func (m *RateLimit) XXX_DiscardUnknown() {
	xxx_messageInfo_RateLimit.DiscardUnknown(m)
}

var xxx_messageInfo_RateLimit proto.InternalMessageInfo

func (m *RateLimit) GetRules() []*Rule {
	if m != nil {
		return m.Rules
	}
	return nil
}

func (m *RateLimit) GetRevision() *wrapperspb.StringValue {
	if m != nil {
		return m.Revision
	}
	return nil
}

// 单个限流规则信息
type Rule struct {
	// 限流规则唯一标识
	Id *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 限流规则所属服务名
	Service *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	// 限流规则所属命名空间
	Namespace *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// 可选，SUBSET标识
	Subset map[string]*model.MatchString `protobuf:"bytes,4,rep,name=subset,proto3" json:"subset,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// 限流规则优先级，0值最高
	Priority *wrapperspb.UInt32Value `protobuf:"bytes,5,opt,name=priority,proto3" json:"priority,omitempty"`
	Resource Rule_Resource           `protobuf:"varint,6,opt,name=resource,proto3,enum=v1.Rule_Resource" json:"resource,omitempty"`
	Type     Rule_Type               `protobuf:"varint,7,opt,name=type,proto3,enum=v1.Rule_Type" json:"type,omitempty"`
	// 业务标签集合，通过KV进行匹配，全部匹配才使用该规则
	Labels map[string]*model.MatchString `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// 限流阈值
	// 可以有多个粒度的配置（比如同时针对秒级，分钟级，天级），匹配一个则进行限流
	// 全局限流模式下，该值为服务配额总量；单机限流模式下，该值为单个节点能处理的配额量
	Amounts []*Amount `protobuf:"bytes,9,rep,name=amounts,proto3" json:"amounts,omitempty"`
	// 限流动作，对应着客户端的插件名字
	Action *wrapperspb.StringValue `protobuf:"bytes,10,opt,name=action,proto3" json:"action,omitempty"`
	// 是否停用该限流规则，默认启用
	Disable *wrapperspb.BoolValue `protobuf:"bytes,11,opt,name=disable,proto3" json:"disable,omitempty"`
	// 限流上报方式，同时支持按固定周期上报，以及达到配额百分比后上报
	Report *Report `protobuf:"bytes,12,opt,name=report,proto3" json:"report,omitempty"`
	// 限流规则创建时间
	Ctime *wrapperspb.StringValue `protobuf:"bytes,13,opt,name=ctime,proto3" json:"ctime,omitempty"`
	// 限流规则修改时间
	Mtime *wrapperspb.StringValue `protobuf:"bytes,14,opt,name=mtime,proto3" json:"mtime,omitempty"`
	// 限流规则revision信息
	Revision *wrapperspb.StringValue `protobuf:"bytes,15,opt,name=revision,proto3" json:"revision,omitempty"`
	// 服务的TOKEN信息，仅用于控制台，discover接口不下发
	ServiceToken *wrapperspb.StringValue `protobuf:"bytes,16,opt,name=service_token,proto3" json:"service_token,omitempty"`
	// 配额调整算法
	Adjuster *AmountAdjuster `protobuf:"bytes,17,opt,name=adjuster,proto3" json:"adjuster,omitempty"`
	// 通配符是否合并计算，默认分开计数
	RegexCombine *wrapperspb.BoolValue `protobuf:"bytes,18,opt,name=regex_combine,proto3" json:"regex_combine,omitempty"`
	AmountMode   Rule_AmountMode       `protobuf:"varint,19,opt,name=amount_mode,json=amountMode,proto3,enum=v1.Rule_AmountMode" json:"amount_mode,omitempty"`
	Failover     Rule_FailoverType     `protobuf:"varint,20,opt,name=failover,proto3,enum=v1.Rule_FailoverType" json:"failover,omitempty"`
	// 分布式限流服务集群
	Cluster *RateLimitCluster `protobuf:"bytes,21,opt,name=cluster,proto3" json:"cluster,omitempty"`
	// 被调接口名
	Method *model.MatchString `protobuf:"bytes,22,opt,name=method,proto3" json:"method,omitempty"`
	// 被调的参数过滤条件，满足过滤条件才进入限流规则
	Arguments []*MatchArgument `protobuf:"bytes,23,rep,name=arguments,proto3" json:"arguments,omitempty"`
	// 限流规则名
	Name *wrapperspb.StringValue `protobuf:"bytes,24,opt,name=name,proto3" json:"name,omitempty"`
	// 限流规则启用时间
	Etime *wrapperspb.StringValue `protobuf:"bytes,25,opt,name=etime,proto3" json:"etime,omitempty"`
	// 最大排队时长，单位秒
	MaxQueueDelay *wrapperspb.UInt32Value `protobuf:"bytes,26,opt,name=max_queue_delay,proto3" json:"max_queue_delay,omitempty"`
	// 系统资源限流配额
	SystemResourceAmount *SystemResourceAmount `protobuf:"bytes,27,opt,name=systemResourceAmount,proto3" json:"systemResourceAmount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Rule) Reset()         { *m = Rule{} }
func (m *Rule) String() string { return proto.CompactTextString(m) }
func (*Rule) ProtoMessage()    {}
func (*Rule) Descriptor() ([]byte, []int) {
	return fileDescriptor_ratelimit_fefd9d07bd36fe0f, []int{1}
}
func (m *Rule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rule.Unmarshal(m, b)
}
func (m *Rule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rule.Marshal(b, m, deterministic)
}
func (dst *Rule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rule.Merge(dst, src)
}
func (m *Rule) XXX_Size() int {
	return xxx_messageInfo_Rule.Size(m)
}
func (m *Rule) XXX_DiscardUnknown() {
	xxx_messageInfo_Rule.DiscardUnknown(m)
}

var xxx_messageInfo_Rule proto.InternalMessageInfo

func (m *Rule) GetId() *wrapperspb.StringValue {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Rule) GetService() *wrapperspb.StringValue {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *Rule) GetNamespace() *wrapperspb.StringValue {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *Rule) GetSubset() map[string]*model.MatchString {
	if m != nil {
		return m.Subset
	}
	return nil
}

func (m *Rule) GetPriority() *wrapperspb.UInt32Value {
	if m != nil {
		return m.Priority
	}
	return nil
}

func (m *Rule) GetResource() Rule_Resource {
	if m != nil {
		return m.Resource
	}
	return Rule_QPS
}

func (m *Rule) GetType() Rule_Type {
	if m != nil {
		return m.Type
	}
	return Rule_GLOBAL
}

func (m *Rule) GetLabels() map[string]*model.MatchString {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Rule) GetAmounts() []*Amount {
	if m != nil {
		return m.Amounts
	}
	return nil
}

func (m *Rule) GetAction() *wrapperspb.StringValue {
	if m != nil {
		return m.Action
	}
	return nil
}

func (m *Rule) GetDisable() *wrapperspb.BoolValue {
	if m != nil {
		return m.Disable
	}
	return nil
}

func (m *Rule) GetReport() *Report {
	if m != nil {
		return m.Report
	}
	return nil
}

func (m *Rule) GetCtime() *wrapperspb.StringValue {
	if m != nil {
		return m.Ctime
	}
	return nil
}

func (m *Rule) GetMtime() *wrapperspb.StringValue {
	if m != nil {
		return m.Mtime
	}
	return nil
}

func (m *Rule) GetRevision() *wrapperspb.StringValue {
	if m != nil {
		return m.Revision
	}
	return nil
}

func (m *Rule) GetServiceToken() *wrapperspb.StringValue {
	if m != nil {
		return m.ServiceToken
	}
	return nil
}

func (m *Rule) GetAdjuster() *AmountAdjuster {
	if m != nil {
		return m.Adjuster
	}
	return nil
}

func (m *Rule) GetRegexCombine() *wrapperspb.BoolValue {
	if m != nil {
		return m.RegexCombine
	}
	return nil
}

func (m *Rule) GetAmountMode() Rule_AmountMode {
	if m != nil {
		return m.AmountMode
	}
	return Rule_GLOBAL_TOTAL
}

func (m *Rule) GetFailover() Rule_FailoverType {
	if m != nil {
		return m.Failover
	}
	return Rule_FAILOVER_LOCAL
}

func (m *Rule) GetCluster() *RateLimitCluster {
	if m != nil {
		return m.Cluster
	}
	return nil
}

func (m *Rule) GetMethod() *model.MatchString {
	if m != nil {
		return m.Method
	}
	return nil
}

func (m *Rule) GetArguments() []*MatchArgument {
	if m != nil {
		return m.Arguments
	}
	return nil
}

func (m *Rule) GetName() *wrapperspb.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *Rule) GetEtime() *wrapperspb.StringValue {
	if m != nil {
		return m.Etime
	}
	return nil
}

func (m *Rule) GetMaxQueueDelay() *wrapperspb.UInt32Value {
	if m != nil {
		return m.MaxQueueDelay
	}
	return nil
}

func (m *Rule) GetSystemResourceAmount() *SystemResourceAmount {
	if m != nil {
		return m.SystemResourceAmount
	}
	return nil
}

type MatchArgument struct {
	Type MatchArgument_Type `protobuf:"varint,1,opt,name=type,proto3,enum=v1.MatchArgument_Type" json:"type,omitempty"`
	// header key or query key
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// header value or query value
	Value                *model.MatchString `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *MatchArgument) Reset()         { *m = MatchArgument{} }
func (m *MatchArgument) String() string { return proto.CompactTextString(m) }
func (*MatchArgument) ProtoMessage()    {}
func (*MatchArgument) Descriptor() ([]byte, []int) {
	return fileDescriptor_ratelimit_fefd9d07bd36fe0f, []int{2}
}
func (m *MatchArgument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchArgument.Unmarshal(m, b)
}
func (m *MatchArgument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchArgument.Marshal(b, m, deterministic)
}
func (dst *MatchArgument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchArgument.Merge(dst, src)
}
func (m *MatchArgument) XXX_Size() int {
	return xxx_messageInfo_MatchArgument.Size(m)
}
func (m *MatchArgument) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchArgument.DiscardUnknown(m)
}

var xxx_messageInfo_MatchArgument proto.InternalMessageInfo

func (m *MatchArgument) GetType() MatchArgument_Type {
	if m != nil {
		return m.Type
	}
	return MatchArgument_CUSTOM
}

func (m *MatchArgument) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *MatchArgument) GetValue() *model.MatchString {
	if m != nil {
		return m.Value
	}
	return nil
}

// 分布式限流服务集群
type RateLimitCluster struct {
	Service *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// 限流规则所属命名空间
	Namespace            *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *RateLimitCluster) Reset()         { *m = RateLimitCluster{} }
func (m *RateLimitCluster) String() string { return proto.CompactTextString(m) }
func (*RateLimitCluster) ProtoMessage()    {}
func (*RateLimitCluster) Descriptor() ([]byte, []int) {
	return fileDescriptor_ratelimit_fefd9d07bd36fe0f, []int{3}
}
func (m *RateLimitCluster) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RateLimitCluster.Unmarshal(m, b)
}
func (m *RateLimitCluster) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RateLimitCluster.Marshal(b, m, deterministic)
}
func (dst *RateLimitCluster) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RateLimitCluster.Merge(dst, src)
}
func (m *RateLimitCluster) XXX_Size() int {
	return xxx_messageInfo_RateLimitCluster.Size(m)
}
func (m *RateLimitCluster) XXX_DiscardUnknown() {
	xxx_messageInfo_RateLimitCluster.DiscardUnknown(m)
}

var xxx_messageInfo_RateLimitCluster proto.InternalMessageInfo

func (m *RateLimitCluster) GetService() *wrapperspb.StringValue {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *RateLimitCluster) GetNamespace() *wrapperspb.StringValue {
	if m != nil {
		return m.Namespace
	}
	return nil
}

// 限流配额
type Amount struct {
	// 时间周期内的最大配额数
	MaxAmount *wrapperspb.UInt32Value `protobuf:"bytes,1,opt,name=maxAmount,proto3" json:"maxAmount,omitempty"`
	// 配额生效的时间周期，必须大于等于1s
	ValidDuration *durationpb.Duration `protobuf:"bytes,2,opt,name=validDuration,proto3" json:"validDuration,omitempty"`
	// 请求统计精度
	Precision *wrapperspb.UInt32Value `protobuf:"bytes,3,opt,name=precision,proto3" json:"precision,omitempty"`
	// 可选，起始限流阈值，爬坡起始值
	StartAmount *wrapperspb.UInt32Value `protobuf:"bytes,4,opt,name=startAmount,proto3" json:"startAmount,omitempty"`
	// 可选，最小限流阈值，降低时最小值
	MinAmount            *wrapperspb.UInt32Value `protobuf:"bytes,5,opt,name=minAmount,proto3" json:"minAmount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Amount) Reset()         { *m = Amount{} }
func (m *Amount) String() string { return proto.CompactTextString(m) }
func (*Amount) ProtoMessage()    {}
func (*Amount) Descriptor() ([]byte, []int) {
	return fileDescriptor_ratelimit_fefd9d07bd36fe0f, []int{4}
}
func (m *Amount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Amount.Unmarshal(m, b)
}
func (m *Amount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Amount.Marshal(b, m, deterministic)
}
func (dst *Amount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Amount.Merge(dst, src)
}
func (m *Amount) XXX_Size() int {
	return xxx_messageInfo_Amount.Size(m)
}
func (m *Amount) XXX_DiscardUnknown() {
	xxx_messageInfo_Amount.DiscardUnknown(m)
}

var xxx_messageInfo_Amount proto.InternalMessageInfo

func (m *Amount) GetMaxAmount() *wrapperspb.UInt32Value {
	if m != nil {
		return m.MaxAmount
	}
	return nil
}

func (m *Amount) GetValidDuration() *durationpb.Duration {
	if m != nil {
		return m.ValidDuration
	}
	return nil
}

func (m *Amount) GetPrecision() *wrapperspb.UInt32Value {
	if m != nil {
		return m.Precision
	}
	return nil
}

func (m *Amount) GetStartAmount() *wrapperspb.UInt32Value {
	if m != nil {
		return m.StartAmount
	}
	return nil
}

func (m *Amount) GetMinAmount() *wrapperspb.UInt32Value {
	if m != nil {
		return m.MinAmount
	}
	return nil
}

// 限流上报方式
type Report struct {
	// 配额固定上报周期，单位毫秒
	Interval *durationpb.Duration `protobuf:"bytes,1,opt,name=interval,proto3" json:"interval,omitempty"`
	// 使用了百分之多少配额后启动一次实时上报，值范围(0,100]
	AmountPercent        *wrapperspb.UInt32Value `protobuf:"bytes,2,opt,name=amountPercent,proto3" json:"amountPercent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Report) Reset()         { *m = Report{} }
func (m *Report) String() string { return proto.CompactTextString(m) }
func (*Report) ProtoMessage()    {}
func (*Report) Descriptor() ([]byte, []int) {
	return fileDescriptor_ratelimit_fefd9d07bd36fe0f, []int{5}
}
func (m *Report) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report.Unmarshal(m, b)
}
func (m *Report) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report.Marshal(b, m, deterministic)
}
func (dst *Report) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report.Merge(dst, src)
}
func (m *Report) XXX_Size() int {
	return xxx_messageInfo_Report.Size(m)
}
func (m *Report) XXX_DiscardUnknown() {
	xxx_messageInfo_Report.DiscardUnknown(m)
}

var xxx_messageInfo_Report proto.InternalMessageInfo

func (m *Report) GetInterval() *durationpb.Duration {
	if m != nil {
		return m.Interval
	}
	return nil
}

func (m *Report) GetAmountPercent() *wrapperspb.UInt32Value {
	if m != nil {
		return m.AmountPercent
	}
	return nil
}

// 配额调整算法
type AmountAdjuster struct {
	Climb                *ClimbConfig `protobuf:"bytes,1,opt,name=climb,proto3" json:"climb,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AmountAdjuster) Reset()         { *m = AmountAdjuster{} }
func (m *AmountAdjuster) String() string { return proto.CompactTextString(m) }
func (*AmountAdjuster) ProtoMessage()    {}
func (*AmountAdjuster) Descriptor() ([]byte, []int) {
	return fileDescriptor_ratelimit_fefd9d07bd36fe0f, []int{6}
}
func (m *AmountAdjuster) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AmountAdjuster.Unmarshal(m, b)
}
func (m *AmountAdjuster) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AmountAdjuster.Marshal(b, m, deterministic)
}
func (dst *AmountAdjuster) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AmountAdjuster.Merge(dst, src)
}
func (m *AmountAdjuster) XXX_Size() int {
	return xxx_messageInfo_AmountAdjuster.Size(m)
}
func (m *AmountAdjuster) XXX_DiscardUnknown() {
	xxx_messageInfo_AmountAdjuster.DiscardUnknown(m)
}

var xxx_messageInfo_AmountAdjuster proto.InternalMessageInfo

func (m *AmountAdjuster) GetClimb() *ClimbConfig {
	if m != nil {
		return m.Climb
	}
	return nil
}

// 限流调整算法Climb相关配置
type ClimbConfig struct {
	Enable               *wrapperspb.BoolValue        `protobuf:"bytes,1,opt,name=enable,proto3" json:"enable,omitempty"`
	Metric               *ClimbConfig_MetricConfig    `protobuf:"bytes,2,opt,name=metric,proto3" json:"metric,omitempty"`
	Policy               *ClimbConfig_TriggerPolicy   `protobuf:"bytes,3,opt,name=policy,proto3" json:"policy,omitempty"`
	Throttling           *ClimbConfig_ClimbThrottling `protobuf:"bytes,4,opt,name=throttling,proto3" json:"throttling,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ClimbConfig) Reset()         { *m = ClimbConfig{} }
func (m *ClimbConfig) String() string { return proto.CompactTextString(m) }
func (*ClimbConfig) ProtoMessage()    {}
func (*ClimbConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_ratelimit_fefd9d07bd36fe0f, []int{7}
}
func (m *ClimbConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClimbConfig.Unmarshal(m, b)
}
func (m *ClimbConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClimbConfig.Marshal(b, m, deterministic)
}
func (dst *ClimbConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClimbConfig.Merge(dst, src)
}
func (m *ClimbConfig) XXX_Size() int {
	return xxx_messageInfo_ClimbConfig.Size(m)
}
func (m *ClimbConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ClimbConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ClimbConfig proto.InternalMessageInfo

func (m *ClimbConfig) GetEnable() *wrapperspb.BoolValue {
	if m != nil {
		return m.Enable
	}
	return nil
}

func (m *ClimbConfig) GetMetric() *ClimbConfig_MetricConfig {
	if m != nil {
		return m.Metric
	}
	return nil
}

func (m *ClimbConfig) GetPolicy() *ClimbConfig_TriggerPolicy {
	if m != nil {
		return m.Policy
	}
	return nil
}

func (m *ClimbConfig) GetThrottling() *ClimbConfig_ClimbThrottling {
	if m != nil {
		return m.Throttling
	}
	return nil
}

// 限流数据统计配置
type ClimbConfig_MetricConfig struct {
	// 限流数据度量周期，默认60s
	Window *durationpb.Duration `protobuf:"bytes,1,opt,name=window,proto3" json:"window,omitempty"`
	// 数据统计精度，决定数据度量的最小周期，度量滑窗的步长=window/precision
	Precision *wrapperspb.UInt32Value `protobuf:"bytes,2,opt,name=precision,proto3" json:"precision,omitempty"`
	// 上报周期，默认20s
	ReportInterval       *durationpb.Duration `protobuf:"bytes,3,opt,name=reportInterval,proto3" json:"reportInterval,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ClimbConfig_MetricConfig) Reset()         { *m = ClimbConfig_MetricConfig{} }
func (m *ClimbConfig_MetricConfig) String() string { return proto.CompactTextString(m) }
func (*ClimbConfig_MetricConfig) ProtoMessage()    {}
func (*ClimbConfig_MetricConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_ratelimit_fefd9d07bd36fe0f, []int{7, 0}
}
func (m *ClimbConfig_MetricConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClimbConfig_MetricConfig.Unmarshal(m, b)
}
func (m *ClimbConfig_MetricConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClimbConfig_MetricConfig.Marshal(b, m, deterministic)
}
func (dst *ClimbConfig_MetricConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClimbConfig_MetricConfig.Merge(dst, src)
}
func (m *ClimbConfig_MetricConfig) XXX_Size() int {
	return xxx_messageInfo_ClimbConfig_MetricConfig.Size(m)
}
func (m *ClimbConfig_MetricConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ClimbConfig_MetricConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ClimbConfig_MetricConfig proto.InternalMessageInfo

func (m *ClimbConfig_MetricConfig) GetWindow() *durationpb.Duration {
	if m != nil {
		return m.Window
	}
	return nil
}

func (m *ClimbConfig_MetricConfig) GetPrecision() *wrapperspb.UInt32Value {
	if m != nil {
		return m.Precision
	}
	return nil
}

func (m *ClimbConfig_MetricConfig) GetReportInterval() *durationpb.Duration {
	if m != nil {
		return m.ReportInterval
	}
	return nil
}

// 触发调整的策略
type ClimbConfig_TriggerPolicy struct {
	ErrorRate            *ClimbConfig_TriggerPolicy_ErrorRate `protobuf:"bytes,1,opt,name=errorRate,proto3" json:"errorRate,omitempty"`
	SlowRate             *ClimbConfig_TriggerPolicy_SlowRate  `protobuf:"bytes,2,opt,name=slowRate,proto3" json:"slowRate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *ClimbConfig_TriggerPolicy) Reset()         { *m = ClimbConfig_TriggerPolicy{} }
func (m *ClimbConfig_TriggerPolicy) String() string { return proto.CompactTextString(m) }
func (*ClimbConfig_TriggerPolicy) ProtoMessage()    {}
func (*ClimbConfig_TriggerPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_ratelimit_fefd9d07bd36fe0f, []int{7, 1}
}
func (m *ClimbConfig_TriggerPolicy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClimbConfig_TriggerPolicy.Unmarshal(m, b)
}
func (m *ClimbConfig_TriggerPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClimbConfig_TriggerPolicy.Marshal(b, m, deterministic)
}
func (dst *ClimbConfig_TriggerPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClimbConfig_TriggerPolicy.Merge(dst, src)
}
func (m *ClimbConfig_TriggerPolicy) XXX_Size() int {
	return xxx_messageInfo_ClimbConfig_TriggerPolicy.Size(m)
}
func (m *ClimbConfig_TriggerPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_ClimbConfig_TriggerPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_ClimbConfig_TriggerPolicy proto.InternalMessageInfo

func (m *ClimbConfig_TriggerPolicy) GetErrorRate() *ClimbConfig_TriggerPolicy_ErrorRate {
	if m != nil {
		return m.ErrorRate
	}
	return nil
}

func (m *ClimbConfig_TriggerPolicy) GetSlowRate() *ClimbConfig_TriggerPolicy_SlowRate {
	if m != nil {
		return m.SlowRate
	}
	return nil
}

// 错误率触发调整配置
type ClimbConfig_TriggerPolicy_ErrorRate struct {
	Enable                 *wrapperspb.BoolValue                                `protobuf:"bytes,1,opt,name=enable,proto3" json:"enable,omitempty"`
	RequestVolumeThreshold *wrapperspb.UInt32Value                              `protobuf:"bytes,2,opt,name=requestVolumeThreshold,proto3" json:"requestVolumeThreshold,omitempty"`
	ErrorRate              *wrapperspb.Int32Value                               `protobuf:"bytes,3,opt,name=errorRate,proto3" json:"errorRate,omitempty"`
	Specials               []*ClimbConfig_TriggerPolicy_ErrorRate_SpecialConfig `protobuf:"bytes,4,rep,name=specials,proto3" json:"specials,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                                             `json:"-"`
	XXX_unrecognized       []byte                                               `json:"-"`
	XXX_sizecache          int32                                                `json:"-"`
}

func (m *ClimbConfig_TriggerPolicy_ErrorRate) Reset()         { *m = ClimbConfig_TriggerPolicy_ErrorRate{} }
func (m *ClimbConfig_TriggerPolicy_ErrorRate) String() string { return proto.CompactTextString(m) }
func (*ClimbConfig_TriggerPolicy_ErrorRate) ProtoMessage()    {}
func (*ClimbConfig_TriggerPolicy_ErrorRate) Descriptor() ([]byte, []int) {
	return fileDescriptor_ratelimit_fefd9d07bd36fe0f, []int{7, 1, 0}
}
func (m *ClimbConfig_TriggerPolicy_ErrorRate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClimbConfig_TriggerPolicy_ErrorRate.Unmarshal(m, b)
}
func (m *ClimbConfig_TriggerPolicy_ErrorRate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClimbConfig_TriggerPolicy_ErrorRate.Marshal(b, m, deterministic)
}
func (dst *ClimbConfig_TriggerPolicy_ErrorRate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClimbConfig_TriggerPolicy_ErrorRate.Merge(dst, src)
}
func (m *ClimbConfig_TriggerPolicy_ErrorRate) XXX_Size() int {
	return xxx_messageInfo_ClimbConfig_TriggerPolicy_ErrorRate.Size(m)
}
func (m *ClimbConfig_TriggerPolicy_ErrorRate) XXX_DiscardUnknown() {
	xxx_messageInfo_ClimbConfig_TriggerPolicy_ErrorRate.DiscardUnknown(m)
}

var xxx_messageInfo_ClimbConfig_TriggerPolicy_ErrorRate proto.InternalMessageInfo

func (m *ClimbConfig_TriggerPolicy_ErrorRate) GetEnable() *wrapperspb.BoolValue {
	if m != nil {
		return m.Enable
	}
	return nil
}

func (m *ClimbConfig_TriggerPolicy_ErrorRate) GetRequestVolumeThreshold() *wrapperspb.UInt32Value {
	if m != nil {
		return m.RequestVolumeThreshold
	}
	return nil
}

func (m *ClimbConfig_TriggerPolicy_ErrorRate) GetErrorRate() *wrapperspb.Int32Value {
	if m != nil {
		return m.ErrorRate
	}
	return nil
}

func (m *ClimbConfig_TriggerPolicy_ErrorRate) GetSpecials() []*ClimbConfig_TriggerPolicy_ErrorRate_SpecialConfig {
	if m != nil {
		return m.Specials
	}
	return nil
}

// 特殊错误码触发调整配置
type ClimbConfig_TriggerPolicy_ErrorRate_SpecialConfig struct {
	Type                 *wrapperspb.StringValue  `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	ErrorCodes           []*wrapperspb.Int64Value `protobuf:"bytes,2,rep,name=errorCodes,proto3" json:"errorCodes,omitempty"`
	ErrorRate            *wrapperspb.Int32Value   `protobuf:"bytes,3,opt,name=errorRate,proto3" json:"errorRate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ClimbConfig_TriggerPolicy_ErrorRate_SpecialConfig) Reset() {
	*m = ClimbConfig_TriggerPolicy_ErrorRate_SpecialConfig{}
}
func (m *ClimbConfig_TriggerPolicy_ErrorRate_SpecialConfig) String() string {
	return proto.CompactTextString(m)
}
func (*ClimbConfig_TriggerPolicy_ErrorRate_SpecialConfig) ProtoMessage() {}
func (*ClimbConfig_TriggerPolicy_ErrorRate_SpecialConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_ratelimit_fefd9d07bd36fe0f, []int{7, 1, 0, 0}
}
func (m *ClimbConfig_TriggerPolicy_ErrorRate_SpecialConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClimbConfig_TriggerPolicy_ErrorRate_SpecialConfig.Unmarshal(m, b)
}
func (m *ClimbConfig_TriggerPolicy_ErrorRate_SpecialConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClimbConfig_TriggerPolicy_ErrorRate_SpecialConfig.Marshal(b, m, deterministic)
}
func (dst *ClimbConfig_TriggerPolicy_ErrorRate_SpecialConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClimbConfig_TriggerPolicy_ErrorRate_SpecialConfig.Merge(dst, src)
}
func (m *ClimbConfig_TriggerPolicy_ErrorRate_SpecialConfig) XXX_Size() int {
	return xxx_messageInfo_ClimbConfig_TriggerPolicy_ErrorRate_SpecialConfig.Size(m)
}
func (m *ClimbConfig_TriggerPolicy_ErrorRate_SpecialConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ClimbConfig_TriggerPolicy_ErrorRate_SpecialConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ClimbConfig_TriggerPolicy_ErrorRate_SpecialConfig proto.InternalMessageInfo

func (m *ClimbConfig_TriggerPolicy_ErrorRate_SpecialConfig) GetType() *wrapperspb.StringValue {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *ClimbConfig_TriggerPolicy_ErrorRate_SpecialConfig) GetErrorCodes() []*wrapperspb.Int64Value {
	if m != nil {
		return m.ErrorCodes
	}
	return nil
}

func (m *ClimbConfig_TriggerPolicy_ErrorRate_SpecialConfig) GetErrorRate() *wrapperspb.Int32Value {
	if m != nil {
		return m.ErrorRate
	}
	return nil
}

// 慢调用触发调整配置
type ClimbConfig_TriggerPolicy_SlowRate struct {
	Enable               *wrapperspb.BoolValue  `protobuf:"bytes,1,opt,name=enable,proto3" json:"enable,omitempty"`
	MaxRt                *durationpb.Duration   `protobuf:"bytes,2,opt,name=maxRt,proto3" json:"maxRt,omitempty"`
	SlowRate             *wrapperspb.Int32Value `protobuf:"bytes,3,opt,name=slowRate,proto3" json:"slowRate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ClimbConfig_TriggerPolicy_SlowRate) Reset()         { *m = ClimbConfig_TriggerPolicy_SlowRate{} }
func (m *ClimbConfig_TriggerPolicy_SlowRate) String() string { return proto.CompactTextString(m) }
func (*ClimbConfig_TriggerPolicy_SlowRate) ProtoMessage()    {}
func (*ClimbConfig_TriggerPolicy_SlowRate) Descriptor() ([]byte, []int) {
	return fileDescriptor_ratelimit_fefd9d07bd36fe0f, []int{7, 1, 1}
}
func (m *ClimbConfig_TriggerPolicy_SlowRate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClimbConfig_TriggerPolicy_SlowRate.Unmarshal(m, b)
}
func (m *ClimbConfig_TriggerPolicy_SlowRate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClimbConfig_TriggerPolicy_SlowRate.Marshal(b, m, deterministic)
}
func (dst *ClimbConfig_TriggerPolicy_SlowRate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClimbConfig_TriggerPolicy_SlowRate.Merge(dst, src)
}
func (m *ClimbConfig_TriggerPolicy_SlowRate) XXX_Size() int {
	return xxx_messageInfo_ClimbConfig_TriggerPolicy_SlowRate.Size(m)
}
func (m *ClimbConfig_TriggerPolicy_SlowRate) XXX_DiscardUnknown() {
	xxx_messageInfo_ClimbConfig_TriggerPolicy_SlowRate.DiscardUnknown(m)
}

var xxx_messageInfo_ClimbConfig_TriggerPolicy_SlowRate proto.InternalMessageInfo

func (m *ClimbConfig_TriggerPolicy_SlowRate) GetEnable() *wrapperspb.BoolValue {
	if m != nil {
		return m.Enable
	}
	return nil
}

func (m *ClimbConfig_TriggerPolicy_SlowRate) GetMaxRt() *durationpb.Duration {
	if m != nil {
		return m.MaxRt
	}
	return nil
}

func (m *ClimbConfig_TriggerPolicy_SlowRate) GetSlowRate() *wrapperspb.Int32Value {
	if m != nil {
		return m.SlowRate
	}
	return nil
}

// 爬坡调整相关参数
type ClimbConfig_ClimbThrottling struct {
	ColdBelowTuneDownRate  *wrapperspb.Int32Value `protobuf:"bytes,1,opt,name=coldBelowTuneDownRate,proto3" json:"coldBelowTuneDownRate,omitempty"`
	ColdBelowTuneUpRate    *wrapperspb.Int32Value `protobuf:"bytes,2,opt,name=coldBelowTuneUpRate,proto3" json:"coldBelowTuneUpRate,omitempty"`
	ColdAboveTuneDownRate  *wrapperspb.Int32Value `protobuf:"bytes,3,opt,name=coldAboveTuneDownRate,proto3" json:"coldAboveTuneDownRate,omitempty"`
	ColdAboveTuneUpRate    *wrapperspb.Int32Value `protobuf:"bytes,4,opt,name=coldAboveTuneUpRate,proto3" json:"coldAboveTuneUpRate,omitempty"`
	LimitThresholdToTuneUp *wrapperspb.Int32Value `protobuf:"bytes,5,opt,name=limitThresholdToTuneUp,proto3" json:"limitThresholdToTuneUp,omitempty"`
	JudgeDuration          *durationpb.Duration   `protobuf:"bytes,6,opt,name=judgeDuration,proto3" json:"judgeDuration,omitempty"`
	TuneUpPeriod           *wrapperspb.Int32Value `protobuf:"bytes,7,opt,name=tuneUpPeriod,proto3" json:"tuneUpPeriod,omitempty"`
	TuneDownPeriod         *wrapperspb.Int32Value `protobuf:"bytes,8,opt,name=tuneDownPeriod,proto3" json:"tuneDownPeriod,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}               `json:"-"`
	XXX_unrecognized       []byte                 `json:"-"`
	XXX_sizecache          int32                  `json:"-"`
}

func (m *ClimbConfig_ClimbThrottling) Reset()         { *m = ClimbConfig_ClimbThrottling{} }
func (m *ClimbConfig_ClimbThrottling) String() string { return proto.CompactTextString(m) }
func (*ClimbConfig_ClimbThrottling) ProtoMessage()    {}
func (*ClimbConfig_ClimbThrottling) Descriptor() ([]byte, []int) {
	return fileDescriptor_ratelimit_fefd9d07bd36fe0f, []int{7, 2}
}
func (m *ClimbConfig_ClimbThrottling) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClimbConfig_ClimbThrottling.Unmarshal(m, b)
}
func (m *ClimbConfig_ClimbThrottling) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClimbConfig_ClimbThrottling.Marshal(b, m, deterministic)
}
func (dst *ClimbConfig_ClimbThrottling) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClimbConfig_ClimbThrottling.Merge(dst, src)
}
func (m *ClimbConfig_ClimbThrottling) XXX_Size() int {
	return xxx_messageInfo_ClimbConfig_ClimbThrottling.Size(m)
}
func (m *ClimbConfig_ClimbThrottling) XXX_DiscardUnknown() {
	xxx_messageInfo_ClimbConfig_ClimbThrottling.DiscardUnknown(m)
}

var xxx_messageInfo_ClimbConfig_ClimbThrottling proto.InternalMessageInfo

func (m *ClimbConfig_ClimbThrottling) GetColdBelowTuneDownRate() *wrapperspb.Int32Value {
	if m != nil {
		return m.ColdBelowTuneDownRate
	}
	return nil
}

func (m *ClimbConfig_ClimbThrottling) GetColdBelowTuneUpRate() *wrapperspb.Int32Value {
	if m != nil {
		return m.ColdBelowTuneUpRate
	}
	return nil
}

func (m *ClimbConfig_ClimbThrottling) GetColdAboveTuneDownRate() *wrapperspb.Int32Value {
	if m != nil {
		return m.ColdAboveTuneDownRate
	}
	return nil
}

func (m *ClimbConfig_ClimbThrottling) GetColdAboveTuneUpRate() *wrapperspb.Int32Value {
	if m != nil {
		return m.ColdAboveTuneUpRate
	}
	return nil
}

func (m *ClimbConfig_ClimbThrottling) GetLimitThresholdToTuneUp() *wrapperspb.Int32Value {
	if m != nil {
		return m.LimitThresholdToTuneUp
	}
	return nil
}

func (m *ClimbConfig_ClimbThrottling) GetJudgeDuration() *durationpb.Duration {
	if m != nil {
		return m.JudgeDuration
	}
	return nil
}

func (m *ClimbConfig_ClimbThrottling) GetTuneUpPeriod() *wrapperspb.Int32Value {
	if m != nil {
		return m.TuneUpPeriod
	}
	return nil
}

func (m *ClimbConfig_ClimbThrottling) GetTuneDownPeriod() *wrapperspb.Int32Value {
	if m != nil {
		return m.TuneDownPeriod
	}
	return nil
}

// 自适应限流阈值
type SystemResourceAmount struct {
	// 采样窗口大小
	Window *durationpb.Duration `protobuf:"bytes,1,opt,name=window,proto3" json:"window,omitempty"`
	// 数据统计精度，决定滑动窗口的最小周期，滑窗的步长=window/precision
	Precision *wrapperspb.UInt32Value `protobuf:"bytes,2,opt,name=precision,proto3" json:"precision,omitempty"`
	// 触发阈值
	Threshold            *wrapperspb.FloatValue `protobuf:"bytes,3,opt,name=threshold,proto3" json:"threshold,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SystemResourceAmount) Reset()         { *m = SystemResourceAmount{} }
func (m *SystemResourceAmount) String() string { return proto.CompactTextString(m) }
func (*SystemResourceAmount) ProtoMessage()    {}
func (*SystemResourceAmount) Descriptor() ([]byte, []int) {
	return fileDescriptor_ratelimit_fefd9d07bd36fe0f, []int{8}
}
func (m *SystemResourceAmount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemResourceAmount.Unmarshal(m, b)
}
func (m *SystemResourceAmount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemResourceAmount.Marshal(b, m, deterministic)
}
func (dst *SystemResourceAmount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemResourceAmount.Merge(dst, src)
}
func (m *SystemResourceAmount) XXX_Size() int {
	return xxx_messageInfo_SystemResourceAmount.Size(m)
}
func (m *SystemResourceAmount) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemResourceAmount.DiscardUnknown(m)
}

var xxx_messageInfo_SystemResourceAmount proto.InternalMessageInfo

func (m *SystemResourceAmount) GetWindow() *durationpb.Duration {
	if m != nil {
		return m.Window
	}
	return nil
}

func (m *SystemResourceAmount) GetPrecision() *wrapperspb.UInt32Value {
	if m != nil {
		return m.Precision
	}
	return nil
}

func (m *SystemResourceAmount) GetThreshold() *wrapperspb.FloatValue {
	if m != nil {
		return m.Threshold
	}
	return nil
}

func init() {
	proto.RegisterType((*RateLimit)(nil), "v1.RateLimit")
	proto.RegisterType((*Rule)(nil), "v1.Rule")
	proto.RegisterMapType((map[string]*model.MatchString)(nil), "v1.Rule.LabelsEntry")
	proto.RegisterMapType((map[string]*model.MatchString)(nil), "v1.Rule.SubsetEntry")
	proto.RegisterType((*MatchArgument)(nil), "v1.MatchArgument")
	proto.RegisterType((*RateLimitCluster)(nil), "v1.RateLimitCluster")
	proto.RegisterType((*Amount)(nil), "v1.Amount")
	proto.RegisterType((*Report)(nil), "v1.Report")
	proto.RegisterType((*AmountAdjuster)(nil), "v1.AmountAdjuster")
	proto.RegisterType((*ClimbConfig)(nil), "v1.ClimbConfig")
	proto.RegisterType((*ClimbConfig_MetricConfig)(nil), "v1.ClimbConfig.MetricConfig")
	proto.RegisterType((*ClimbConfig_TriggerPolicy)(nil), "v1.ClimbConfig.TriggerPolicy")
	proto.RegisterType((*ClimbConfig_TriggerPolicy_ErrorRate)(nil), "v1.ClimbConfig.TriggerPolicy.ErrorRate")
	proto.RegisterType((*ClimbConfig_TriggerPolicy_ErrorRate_SpecialConfig)(nil), "v1.ClimbConfig.TriggerPolicy.ErrorRate.SpecialConfig")
	proto.RegisterType((*ClimbConfig_TriggerPolicy_SlowRate)(nil), "v1.ClimbConfig.TriggerPolicy.SlowRate")
	proto.RegisterType((*ClimbConfig_ClimbThrottling)(nil), "v1.ClimbConfig.ClimbThrottling")
	proto.RegisterType((*SystemResourceAmount)(nil), "v1.SystemResourceAmount")
	proto.RegisterEnum("v1.Rule_Resource", Rule_Resource_name, Rule_Resource_value)
	proto.RegisterEnum("v1.Rule_Type", Rule_Type_name, Rule_Type_value)
	proto.RegisterEnum("v1.Rule_AmountMode", Rule_AmountMode_name, Rule_AmountMode_value)
	proto.RegisterEnum("v1.Rule_FailoverType", Rule_FailoverType_name, Rule_FailoverType_value)
	proto.RegisterEnum("v1.MatchArgument_Type", MatchArgument_Type_name, MatchArgument_Type_value)
}

func init() { proto.RegisterFile("ratelimit.proto", fileDescriptor_ratelimit_fefd9d07bd36fe0f) }

var fileDescriptor_ratelimit_fefd9d07bd36fe0f = []byte{
	// 1654 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x58, 0xdd, 0x72, 0xdb, 0xc6,
	0x15, 0x36, 0x48, 0x8a, 0x22, 0x0f, 0x45, 0x09, 0x5e, 0xff, 0x14, 0x61, 0x9a, 0xd4, 0xe5, 0xb4,
	0x8d, 0xa7, 0x93, 0x82, 0x95, 0x62, 0xc7, 0x49, 0x3a, 0x53, 0x97, 0xa4, 0xe8, 0x5a, 0x1d, 0x2a,
	0x92, 0x96, 0x94, 0xa7, 0xee, 0x0d, 0x07, 0x04, 0x57, 0xd4, 0x26, 0x00, 0x96, 0x59, 0x2c, 0x28,
	0xeb, 0xba, 0x33, 0xbd, 0xed, 0x63, 0xb4, 0xaf, 0xd0, 0x8b, 0xce, 0xe4, 0x09, 0x3a, 0x7d, 0x83,
	0x4e, 0x1f, 0xa1, 0x6f, 0xd0, 0xd9, 0xc5, 0x12, 0x04, 0xa8, 0x1f, 0xc2, 0xf6, 0x4c, 0xee, 0xa0,
	0x3d, 0xdf, 0x77, 0xf6, 0xec, 0x39, 0xdf, 0x9e, 0xb3, 0x14, 0xec, 0x70, 0x47, 0x10, 0x8f, 0xfa,
	0x54, 0xd8, 0x33, 0xce, 0x04, 0x43, 0x85, 0xf9, 0x6e, 0xe3, 0xe3, 0x29, 0x63, 0x53, 0x8f, 0xb4,
	0xd4, 0xca, 0x38, 0x3a, 0x6b, 0x5d, 0x70, 0x67, 0x36, 0x23, 0x3c, 0x8c, 0x31, 0x57, 0xed, 0x93,
	0x88, 0x3b, 0x82, 0xb2, 0x40, 0xdb, 0x6b, 0x3e, 0x9b, 0x10, 0x2f, 0xfe, 0xa3, 0x49, 0xa0, 0x8a,
	0x1d, 0x41, 0xfa, 0x72, 0x0f, 0xf4, 0x31, 0x6c, 0xf0, 0xc8, 0x23, 0xa1, 0x65, 0x3c, 0x2a, 0x3e,
	0xae, 0xed, 0x55, 0xec, 0xf9, 0xae, 0x8d, 0x23, 0x8f, 0xe0, 0x78, 0x19, 0x7d, 0x01, 0x15, 0x4e,
	0xe6, 0x34, 0xa4, 0x2c, 0xb0, 0x0a, 0x8f, 0x8c, 0xc7, 0xb5, 0xbd, 0x1f, 0xdb, 0xf1, 0x66, 0xf6,
	0x62, 0x33, 0x7b, 0x20, 0x38, 0x0d, 0xa6, 0xaf, 0x1c, 0x2f, 0x22, 0x38, 0x41, 0x37, 0xff, 0x5b,
	0x87, 0x92, 0xf4, 0x84, 0x3e, 0x85, 0x02, 0x9d, 0x58, 0x46, 0x0e, 0x72, 0x81, 0x4e, 0xd0, 0xe7,
	0xb0, 0x19, 0x12, 0x3e, 0xa7, 0x2e, 0xc9, 0xb5, 0xdf, 0x02, 0x8c, 0xbe, 0x82, 0x6a, 0xe0, 0xf8,
	0x24, 0x9c, 0x39, 0x2e, 0xb1, 0x8a, 0x39, 0x98, 0x4b, 0x38, 0xfa, 0x14, 0xca, 0x61, 0x34, 0x0e,
	0x89, 0xb0, 0x4a, 0x2a, 0x0b, 0xf7, 0x17, 0x59, 0xb0, 0x07, 0x6a, 0xb9, 0x17, 0x08, 0x7e, 0x89,
	0x35, 0x46, 0xa6, 0x64, 0xc6, 0x29, 0xe3, 0x54, 0x5c, 0x5a, 0x1b, 0x37, 0x6c, 0x74, 0x7a, 0x10,
	0x88, 0xcf, 0xf6, 0x74, 0x4a, 0x16, 0x68, 0xf4, 0x2b, 0x99, 0xcc, 0x90, 0x45, 0xdc, 0x25, 0x56,
	0xf9, 0x91, 0xf1, 0x78, 0x7b, 0xef, 0x6e, 0xb2, 0x13, 0xd6, 0x06, 0x9c, 0x40, 0xd0, 0x4f, 0xa1,
	0x24, 0x2e, 0x67, 0xc4, 0xda, 0x54, 0xd0, 0x7a, 0x02, 0x1d, 0x5e, 0xce, 0x08, 0x56, 0x26, 0x19,
	0xb9, 0xe7, 0x8c, 0x89, 0x17, 0x5a, 0x95, 0x95, 0xc8, 0xfb, 0x6a, 0x59, 0x47, 0x1e, 0x63, 0xd0,
	0xcf, 0x60, 0xd3, 0xf1, 0x59, 0x14, 0x88, 0xd0, 0xaa, 0x2a, 0x38, 0x48, 0x78, 0x5b, 0x2d, 0xe1,
	0x85, 0x09, 0x3d, 0x81, 0xb2, 0xe3, 0x4a, 0xf1, 0x58, 0x90, 0x23, 0x8d, 0x1a, 0x8b, 0x9e, 0xc0,
	0xe6, 0x84, 0x86, 0xce, 0xd8, 0x23, 0x56, 0x4d, 0xd1, 0x1a, 0x57, 0x68, 0x1d, 0xc6, 0x3c, 0x5d,
	0x35, 0x0d, 0x45, 0x4d, 0x28, 0x73, 0x32, 0x63, 0x5c, 0x58, 0x5b, 0x8a, 0xa4, 0x02, 0xc2, 0x6a,
	0x05, 0x6b, 0x0b, 0xda, 0x83, 0x0d, 0x57, 0x50, 0x9f, 0x58, 0xf5, 0x1c, 0xe1, 0xc4, 0x50, 0xc9,
	0xf1, 0x15, 0x67, 0x3b, 0x0f, 0x47, 0x41, 0x33, 0x52, 0xdf, 0x79, 0x1b, 0xa9, 0xa3, 0x0e, 0xd4,
	0xb5, 0x0c, 0x47, 0x82, 0x7d, 0x4b, 0x02, 0xcb, 0xcc, 0x41, 0xcf, 0x52, 0x90, 0x0d, 0x15, 0x67,
	0xf2, 0x4d, 0x14, 0x0a, 0xc2, 0xad, 0xbb, 0x8a, 0x8e, 0x96, 0xc5, 0x69, 0x6b, 0x0b, 0x4e, 0x30,
	0xe8, 0x77, 0x50, 0xe7, 0x64, 0x4a, 0xde, 0x8c, 0x5c, 0xe6, 0x8f, 0x69, 0x40, 0x2c, 0xb4, 0x36,
	0xeb, 0x59, 0x02, 0x7a, 0x02, 0xb5, 0xb8, 0xe4, 0x23, 0xd9, 0x1d, 0xac, 0x7b, 0x4a, 0x65, 0xf7,
	0x12, 0x01, 0xc5, 0x3b, 0x1f, 0xb2, 0x09, 0xc1, 0xe0, 0x24, 0xdf, 0x68, 0x17, 0x2a, 0x67, 0x0e,
	0xf5, 0xd8, 0x9c, 0x70, 0xeb, 0xbe, 0xa2, 0x3c, 0x48, 0x28, 0x2f, 0xb4, 0x41, 0x09, 0x34, 0x81,
	0x21, 0x1b, 0x36, 0x5d, 0x2f, 0x3e, 0xd9, 0x03, 0x15, 0x64, 0xac, 0xd2, 0x45, 0x0f, 0xea, 0xc6,
	0x36, 0xbc, 0x00, 0xa1, 0x4f, 0xa0, 0xec, 0x13, 0x71, 0xce, 0x26, 0xd6, 0x43, 0x05, 0xdf, 0x91,
	0xf0, 0x43, 0x47, 0xb8, 0xe7, 0x71, 0xfe, 0xb0, 0x36, 0xa3, 0x16, 0x54, 0x1d, 0x3e, 0x8d, 0x7c,
	0x22, 0x15, 0xfd, 0x23, 0xa5, 0xe8, 0xbb, 0x09, 0xb6, 0xad, 0x2d, 0x78, 0x89, 0x41, 0xbf, 0x86,
	0x92, 0xbc, 0xf5, 0x96, 0x95, 0xa3, 0x3e, 0x0a, 0x29, 0x85, 0x44, 0x94, 0x90, 0x3e, 0xc8, 0x23,
	0x24, 0x05, 0x45, 0x2f, 0x60, 0xc7, 0x77, 0xde, 0x8c, 0xbe, 0x8b, 0x48, 0x44, 0x46, 0x13, 0xe2,
	0x39, 0x97, 0x56, 0x23, 0x47, 0x9f, 0x58, 0x25, 0xa1, 0x3e, 0xdc, 0x0f, 0x2f, 0x43, 0x41, 0xfc,
	0x45, 0x6f, 0x88, 0x4b, 0x62, 0x7d, 0xa8, 0x9c, 0x59, 0xf2, 0xa4, 0x83, 0x6b, 0xec, 0xf8, 0x5a,
	0x56, 0xe3, 0x0f, 0x50, 0x4b, 0x75, 0x33, 0x64, 0x42, 0xf1, 0x5b, 0x72, 0xa9, 0xda, 0x72, 0x15,
	0xcb, 0x4f, 0xf4, 0x73, 0xd8, 0x98, 0xcb, 0x40, 0x74, 0xdf, 0xbd, 0x92, 0xf5, 0xd8, 0xfa, 0x55,
	0xe1, 0x0b, 0x43, 0xfa, 0x4a, 0xf5, 0x97, 0xf7, 0xf2, 0xd5, 0xdc, 0x85, 0xca, 0x22, 0x52, 0xb4,
	0x09, 0xc5, 0x93, 0xe3, 0x81, 0x79, 0x07, 0xed, 0x40, 0xad, 0x7b, 0xf4, 0x75, 0xf7, 0x14, 0xe3,
	0xde, 0xd7, 0xdd, 0xd7, 0xa6, 0x81, 0x6a, 0xb0, 0xd9, 0x3d, 0x3e, 0x1d, 0x75, 0x3a, 0xd8, 0x2c,
	0x34, 0x3f, 0x82, 0x92, 0x94, 0x18, 0x02, 0x28, 0xff, 0xbe, 0x7f, 0xd4, 0x69, 0xf7, 0xcd, 0x3b,
	0xa8, 0x0a, 0x1b, 0xfd, 0xa3, 0x6e, 0xbb, 0x6f, 0x4a, 0x8f, 0xb0, 0x14, 0x2f, 0x32, 0x61, 0x2b,
	0x06, 0x8d, 0x86, 0x47, 0x43, 0x05, 0xbd, 0x0b, 0xf5, 0xc1, 0xcb, 0x36, 0xee, 0x8d, 0x7a, 0x27,
	0xa7, 0xed, 0x7e, 0xff, 0xb5, 0x69, 0x34, 0x9f, 0xc2, 0x56, 0x5a, 0xbc, 0x08, 0xc1, 0xf6, 0x8b,
	0xf6, 0x41, 0xff, 0xe8, 0x55, 0x0f, 0x8f, 0x62, 0xb7, 0x8a, 0x96, 0xac, 0x1d, 0xb7, 0x07, 0x03,
	0xd3, 0x68, 0xfe, 0xcb, 0x80, 0x7a, 0x46, 0x6c, 0xe8, 0x97, 0xba, 0x67, 0x1b, 0xea, 0x6a, 0x3c,
	0xbc, 0xa2, 0xc6, 0x74, 0xf3, 0xd6, 0x69, 0x2b, 0x5c, 0x93, 0xb6, 0xe2, 0x6d, 0x69, 0x6b, 0xfe,
	0x71, 0x79, 0xfe, 0xee, 0xe9, 0x60, 0x78, 0x74, 0x68, 0xde, 0x91, 0xdf, 0x87, 0xbd, 0xe1, 0xcb,
	0xa3, 0x7d, 0xd3, 0x90, 0xdf, 0x2f, 0x7b, 0xed, 0xfd, 0x1e, 0x36, 0x0b, 0x32, 0x2f, 0x27, 0xa7,
	0x3d, 0xfc, 0xda, 0x2c, 0xca, 0x43, 0x75, 0xdb, 0xfd, 0x7e, 0x0f, 0x8f, 0x06, 0x3d, 0xfc, 0xea,
	0xa0, 0xdb, 0x33, 0x4b, 0xa8, 0x0e, 0x55, 0xbd, 0x76, 0x70, 0x6c, 0x6e, 0x34, 0xff, 0x62, 0x80,
	0xb9, 0x7a, 0x31, 0xd3, 0x23, 0xd9, 0x78, 0xe7, 0x91, 0x5c, 0x78, 0xab, 0x91, 0xdc, 0xfc, 0x67,
	0x01, 0xca, 0x71, 0x11, 0xa5, 0x1b, 0xdf, 0x79, 0xa3, 0xb5, 0x6f, 0xe4, 0xb8, 0x48, 0x4b, 0x38,
	0x7a, 0x0e, 0xf5, 0xb9, 0xe3, 0xd1, 0xc9, 0xbe, 0x7e, 0x0f, 0xe9, 0x30, 0x3e, 0xb8, 0xc2, 0x5f,
	0x00, 0x70, 0x16, 0x2f, 0x37, 0x9f, 0x71, 0xe2, 0xc6, 0x53, 0xa1, 0x98, 0x67, 0xf3, 0x04, 0x8e,
	0x7e, 0x0b, 0xb5, 0x50, 0x38, 0x5c, 0xe8, 0xd0, 0x4b, 0x39, 0xd8, 0x69, 0x82, 0x3a, 0x38, 0x0d,
	0x34, 0x7b, 0x23, 0xd7, 0xc1, 0x17, 0xf0, 0xe6, 0x9f, 0x0d, 0x28, 0xc7, 0x73, 0x14, 0x3d, 0x85,
	0x0a, 0x0d, 0x04, 0xe1, 0x73, 0xc7, 0xd3, 0xe9, 0xbb, 0xe5, 0xf8, 0x09, 0x54, 0x0e, 0xb5, 0xb8,
	0xed, 0x1f, 0x13, 0xee, 0x92, 0x40, 0xdc, 0x58, 0xc1, 0x74, 0x04, 0x59, 0x4a, 0xf3, 0x19, 0x6c,
	0x67, 0x07, 0x98, 0x54, 0xb8, 0xeb, 0x51, 0x7f, 0xac, 0x23, 0x51, 0x0a, 0xef, 0xca, 0x85, 0x2e,
	0x0b, 0xce, 0xe8, 0x14, 0xc7, 0xd6, 0xe6, 0xbf, 0xb7, 0xa1, 0x96, 0x5a, 0x46, 0x7b, 0x50, 0x26,
	0x81, 0x7a, 0x5c, 0x18, 0x6b, 0xc7, 0x9c, 0x46, 0xca, 0x77, 0x8c, 0x4f, 0x04, 0xa7, 0x6e, 0x12,
	0x79, 0x76, 0x2f, 0xfb, 0x50, 0x59, 0xf5, 0xc6, 0x1a, 0x8b, 0x9e, 0x42, 0x79, 0xc6, 0x3c, 0xea,
	0x5e, 0xea, 0x6a, 0x7f, 0xb4, 0xca, 0x1a, 0x72, 0x3a, 0x9d, 0x12, 0x7e, 0xac, 0x40, 0x58, 0x83,
	0xd1, 0x73, 0x00, 0x71, 0xce, 0x99, 0x10, 0x1e, 0x0d, 0xa6, 0xba, 0xd4, 0x3f, 0x59, 0xa5, 0xaa,
	0xef, 0x61, 0x02, 0xc3, 0x29, 0x4a, 0xe3, 0x7b, 0x03, 0xb6, 0xd2, 0x01, 0xa1, 0x5d, 0x28, 0x5f,
	0xd0, 0x60, 0xc2, 0x2e, 0xd6, 0x17, 0x4d, 0x03, 0xb3, 0x62, 0x2d, 0xbc, 0x9d, 0x58, 0xdb, 0xb0,
	0x1d, 0xbf, 0xb7, 0x0e, 0x16, 0x5a, 0x29, 0xae, 0xdb, 0x76, 0x85, 0xd0, 0xf8, 0x5b, 0x19, 0xea,
	0x99, 0xec, 0xa0, 0x1e, 0x54, 0x09, 0xe7, 0x8c, 0xcb, 0x96, 0xa2, 0x8f, 0xf1, 0xc9, 0xad, 0xf9,
	0xb4, 0x7b, 0x0b, 0x38, 0x5e, 0x32, 0x51, 0x07, 0x2a, 0xa1, 0xc7, 0x2e, 0x94, 0x97, 0xf8, 0x58,
	0xbf, 0xb8, 0xdd, 0xcb, 0x40, 0xa3, 0x71, 0xc2, 0x6b, 0xfc, 0xa7, 0x08, 0xd5, 0xc4, 0xf9, 0x3b,
	0xe9, 0x69, 0x08, 0x0f, 0x39, 0xf9, 0x2e, 0x22, 0xa1, 0x78, 0xc5, 0xbc, 0xc8, 0x27, 0xc3, 0x73,
	0x4e, 0xc2, 0x73, 0xe6, 0x4d, 0x72, 0xa5, 0xfa, 0x06, 0x2e, 0xfa, 0x32, 0x9d, 0xa2, 0x38, 0xe5,
	0x1f, 0x5e, 0x71, 0x94, 0x2e, 0xd9, 0x32, 0x2d, 0x27, 0x50, 0x09, 0x67, 0xc4, 0xa5, 0x8e, 0x17,
	0xea, 0x1f, 0x2e, 0x4f, 0x73, 0x26, 0xd7, 0x1e, 0xc4, 0x3c, 0xad, 0xfd, 0xc4, 0x4d, 0xe3, 0x1f,
	0x06, 0xd4, 0x33, 0x36, 0xf9, 0x64, 0x4a, 0x06, 0xda, 0xda, 0x27, 0x93, 0x1a, 0x6b, 0xbf, 0x01,
	0x50, 0x31, 0x76, 0xd9, 0x84, 0x84, 0x56, 0x41, 0x05, 0x76, 0xed, 0x91, 0x3e, 0x7f, 0x12, 0xd3,
	0x52, 0xf0, 0xf7, 0x48, 0x47, 0xe3, 0xef, 0x06, 0x54, 0x16, 0x85, 0x7f, 0xa7, 0x02, 0xb7, 0x60,
	0xc3, 0x77, 0xde, 0x60, 0xb1, 0x7e, 0x48, 0xc4, 0x38, 0xf4, 0x2c, 0xa5, 0xcb, 0x1c, 0xb1, 0x2e,
	0xc5, 0xf8, 0xbf, 0x12, 0xec, 0xac, 0x34, 0x03, 0x74, 0x02, 0x0f, 0x5c, 0xe6, 0x4d, 0x3a, 0xc4,
	0x63, 0x17, 0xc3, 0x28, 0x20, 0xfb, 0xec, 0x22, 0x48, 0xdd, 0x9b, 0x5b, 0x3d, 0x5f, 0xcf, 0x44,
	0x87, 0x70, 0x2f, 0x63, 0x38, 0x9d, 0xa5, 0xae, 0xd0, 0xad, 0x0e, 0xaf, 0xe3, 0x2d, 0x22, 0x6c,
	0x8f, 0xd9, 0x9c, 0x64, 0x22, 0x2c, 0xe6, 0x8c, 0xf0, 0x0a, 0x73, 0x11, 0x61, 0x62, 0xd0, 0x11,
	0x96, 0x72, 0x46, 0xb8, 0xc2, 0x43, 0x03, 0x78, 0xa8, 0xfe, 0x75, 0x92, 0x5c, 0xaf, 0x21, 0x8b,
	0xad, 0x7a, 0x7c, 0xde, 0xea, 0xf1, 0x06, 0xaa, 0x7c, 0x43, 0x7c, 0x13, 0x4d, 0xa6, 0x24, 0x79,
	0x43, 0x94, 0xd7, 0xbe, 0x21, 0x32, 0x78, 0xf4, 0x1c, 0xb6, 0x84, 0x72, 0x75, 0x4c, 0x38, 0x65,
	0x13, 0xf5, 0x7b, 0x7e, 0x4d, 0x2c, 0x19, 0x02, 0xea, 0xc2, 0xb6, 0xd0, 0x59, 0xd3, 0x2e, 0x2a,
	0xeb, 0x5d, 0xac, 0x50, 0x9a, 0xdf, 0x1b, 0x70, 0xff, 0xba, 0x9f, 0x0b, 0x3f, 0xf4, 0xa0, 0xf9,
	0x12, 0xaa, 0x22, 0xe9, 0x9c, 0x37, 0x29, 0xe7, 0x85, 0xc7, 0x1c, 0xa1, 0xa9, 0x09, 0xba, 0xf3,
	0x57, 0x03, 0x9e, 0xb9, 0xcc, 0xb7, 0x05, 0x09, 0xe4, 0xf3, 0xc2, 0x9e, 0x31, 0xcf, 0xe1, 0x34,
	0xb4, 0x55, 0xfb, 0x3a, 0xa3, 0x6e, 0xfc, 0x2f, 0x2f, 0x67, 0x46, 0x65, 0x1b, 0x14, 0xdc, 0x39,
	0x3b, 0xa3, 0xae, 0xed, 0x3b, 0x81, 0x33, 0x25, 0x9d, 0xed, 0xe4, 0x59, 0x7b, 0x2c, 0x37, 0xf9,
	0xd3, 0xfe, 0x94, 0x8a, 0xf3, 0x68, 0x6c, 0xbb, 0xcc, 0x6f, 0x69, 0x3f, 0x3e, 0x09, 0xcf, 0x5b,
	0x19, 0x5f, 0xad, 0x38, 0x51, 0xad, 0x29, 0x6b, 0x39, 0x33, 0xda, 0x9a, 0xef, 0xb6, 0xb4, 0xd7,
	0x51, 0xec, 0x75, 0x5c, 0x56, 0x11, 0x7f, 0xf6, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0x72, 0xff,
	0x98, 0x36, 0xb6, 0x13, 0x00, 0x00,
}
