# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ...traffic_manage.ratelimiter import ratelimiter_pb2 as ratelimiter__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in grpcapi_ratelimiter_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RateLimitGRPCV2Stub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Service = channel.stream_stream(
                '/polaris.metric.v2.RateLimitGRPCV2/Service',
                request_serializer=ratelimiter__pb2.RateLimitRequest.SerializeToString,
                response_deserializer=ratelimiter__pb2.RateLimitResponse.FromString,
                _registered_method=True)
        self.TimeAdjust = channel.unary_unary(
                '/polaris.metric.v2.RateLimitGRPCV2/TimeAdjust',
                request_serializer=ratelimiter__pb2.TimeAdjustRequest.SerializeToString,
                response_deserializer=ratelimiter__pb2.TimeAdjustResponse.FromString,
                _registered_method=True)


class RateLimitGRPCV2Servicer:
    """Missing associated documentation comment in .proto file."""

    def Service(self, request_iterator, context):
        """限流接口
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TimeAdjust(self, request, context):
        """时间对齐接口
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RateLimitGRPCV2Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Service': grpc.stream_stream_rpc_method_handler(
                    servicer.Service,
                    request_deserializer=ratelimiter__pb2.RateLimitRequest.FromString,
                    response_serializer=ratelimiter__pb2.RateLimitResponse.SerializeToString,
            ),
            'TimeAdjust': grpc.unary_unary_rpc_method_handler(
                    servicer.TimeAdjust,
                    request_deserializer=ratelimiter__pb2.TimeAdjustRequest.FromString,
                    response_serializer=ratelimiter__pb2.TimeAdjustResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'polaris.metric.v2.RateLimitGRPCV2', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('polaris.metric.v2.RateLimitGRPCV2', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RateLimitGRPCV2:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Service(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/polaris.metric.v2.RateLimitGRPCV2/Service',
            ratelimiter__pb2.RateLimitRequest.SerializeToString,
            ratelimiter__pb2.RateLimitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TimeAdjust(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polaris.metric.v2.RateLimitGRPCV2/TimeAdjust',
            ratelimiter__pb2.TimeAdjustRequest.SerializeToString,
            ratelimiter__pb2.TimeAdjustResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
